"""Generate 1000 unique one-sentence answer sets for 5 personality questions."""

import json
import random

random.seed(42)

QUESTIONS = [
    "What are your biggest motivations?",
    "What are your biggest weaknesses? Strengths?",
    "What activities do you do to handle stress or recharge?",
    "Do you think or act first?",
    "Do you work better alone or with a group?",
]

# --- Q1: Motivations ---
q1_templates = [
    "My family keeps me going every day.",
    "I'm driven by the desire to leave a lasting impact.",
    "Financial independence is what pushes me forward.",
    "I want to prove to myself that I can do hard things.",
    "Curiosity about how the world works motivates me the most.",
    "I'm motivated by the people who said I couldn't do it.",
    "Making my parents proud is my biggest motivation.",
    "I want to build something that outlives me.",
    "Helping others succeed gives me the most energy.",
    "I'm chasing the feeling of mastery over a craft.",
    "Creative expression is what gets me out of bed.",
    "I want to travel the world and experience every culture.",
    "Competition drives me more than anything else.",
    "I'm motivated by solving problems nobody else can crack.",
    "Providing for the people I love keeps me focused.",
    "I want to understand the universe at the deepest level.",
    "Recognition for my work honestly motivates me a lot.",
    "I'm driven by fear of wasting my potential.",
    "Building meaningful relationships is my core motivation.",
    "I want to create art that makes people feel something.",
    "The pursuit of knowledge is what drives me.",
    "I'm motivated by the challenge of constant self-improvement.",
    "Leaving the world better than I found it matters most.",
    "I want to be the best at what I do, period.",
    "Freedom to live life on my own terms motivates me.",
    "I'm driven by the thrill of discovering new ideas.",
    "Security and stability for my future family push me.",
    "I want to mentor the next generation of leaders.",
    "Adventure and new experiences are what I live for.",
    "I'm motivated by the satisfaction of finishing what I start.",
    "Making a difference in my community drives everything I do.",
    "I want to build wealth so I can give it away.",
    "I'm chasing intellectual fulfillment above all else.",
    "The love and support of my friends keeps me going.",
    "I want to innovate and disrupt outdated systems.",
    "Personal growth and becoming a better person daily motivates me.",
    "I'm driven by deadlines and external pressure honestly.",
    "I want to understand human behavior and why we do what we do.",
    "Music and art fuel every decision I make.",
    "I'm motivated by the idea of retiring early.",
    "Teaching and sharing what I know gives me purpose.",
    "I want to write something that changes how people think.",
    "The fear of mediocrity pushes me harder than anything.",
    "I'm driven by loyalty to the people in my corner.",
    "I want to solve climate change or at least contribute.",
    "Seeing tangible results from my work is what drives me.",
    "I'm motivated by spiritual growth and inner peace.",
    "I want to start a business and be my own boss.",
    "The excitement of learning something new never gets old for me.",
    "I'm driven by a deep need to create order from chaos.",
    "Health and longevity motivate my daily choices.",
    "I want to code something that millions of people use.",
    "Being independent and self-sufficient is my biggest driver.",
    "I'm motivated by the stories of people who overcame adversity.",
    "I want to design beautiful things that solve real problems.",
    "Passion for science and discovery fuels everything.",
    "I'm driven by the need to express what words can't capture.",
    "I want to build a legacy my kids can be proud of.",
    "Competitive sports taught me to always push for more.",
    "I'm motivated by the quiet satisfaction of a job well done.",
    "I want to make complex ideas accessible to everyone.",
    "The possibility of what tomorrow could bring keeps me going.",
    "I'm driven by justice and making things fair for people.",
    "I want to cook food that brings people together.",
    "Achieving flow state in my work is the ultimate motivation.",
    "I'm motivated by the beauty I see in mathematics.",
    "I want to explore space, even if just through research.",
    "Being useful to the people around me drives me.",
    "I'm chasing the version of myself I know I can become.",
    "I want to document life through photography and film.",
    "My faith and beliefs are my deepest motivation.",
    "I'm driven by the rush of closing a big deal.",
    "I want to heal people, whether through medicine or kindness.",
    "The hunger to keep learning is what wakes me up.",
    "I'm motivated by proving that my background doesn't define me.",
    "I want to connect people who would never meet otherwise.",
    "Building systems that run without me is deeply satisfying.",
    "I'm driven by empathy and the desire to reduce suffering.",
    "I want to stand on stage and inspire thousands.",
    "Quiet discipline and daily habits are my real motivation.",
    "I'm motivated by the intersection of technology and humanity.",
    "I want to read every book that matters.",
    "The challenge of figuring things out keeps me hooked.",
    "I'm driven by gratitude for the opportunities I've been given.",
    "I want to be someone my younger self would look up to.",
    "Solving puzzles and cracking codes is genuinely what drives me.",
    "I'm motivated by the people counting on me to show up.",
    "I want to produce music that becomes a soundtrack to people's lives.",
    "The promise of a better future motivates my sacrifices today.",
    "I'm driven by an obsessive need to optimize everything.",
    "I want to grow food and live sustainably off the land.",
    "Being part of something bigger than myself motivates me.",
    "I'm chasing the moment when everything I've worked for clicks.",
    "I want to understand consciousness and what it means to be alive.",
    "My competitive nature won't let me settle for second place.",
    "I'm motivated by the possibility of changing someone's life.",
    "I want to build bridges, literally or metaphorically.",
    "The fear of regret is honestly my strongest motivator.",
    "I'm driven by an intense love for what I study.",
]

# --- Q2: Weaknesses and strengths ---
q2_templates = [
    "I overthink everything, but I'm great at planning ahead.",
    "I procrastinate under pressure, though my creativity saves me.",
    "I'm too trusting of people, but that also makes me empathetic.",
    "I struggle with public speaking, but I write exceptionally well.",
    "My impatience is a weakness, but it makes me efficient.",
    "I take on too much, though my work ethic is unmatched.",
    "I avoid conflict, but I'm a great mediator when I step up.",
    "I'm bad at delegating, but I deliver high-quality work.",
    "I get distracted easily, though I'm incredibly resourceful.",
    "I'm a perfectionist which slows me down, but my output is polished.",
    "I struggle with boundaries, but I'm deeply compassionate.",
    "I'm disorganized on the surface, but my ideas are always original.",
    "I second-guess myself, yet I'm excellent at critical analysis.",
    "I'm stubborn when I believe in something, but that persistence pays off.",
    "I have trouble saying no, though people trust me because of it.",
    "I'm not great with numbers, but I have strong emotional intelligence.",
    "I tend to isolate when stressed, but I recharge fast and come back strong.",
    "I'm blunt to a fault, but people always know where they stand with me.",
    "I'm slow to warm up socially, but I form incredibly deep bonds.",
    "I struggle with routine, though I thrive in creative environments.",
    "My weakness is being too competitive, but it drives results.",
    "I can be indecisive, but I see every angle of a problem.",
    "I'm not a morning person, but I do my best work late at night.",
    "I talk too much sometimes, but I'm an excellent communicator.",
    "I'm terrible at small talk, though I excel in deep conversations.",
    "I get emotionally invested, but that passion is also my strength.",
    "I'm risk-averse, but I'm incredibly reliable and consistent.",
    "I can be too analytical, though that makes me a great problem solver.",
    "I'm not great at asking for help, but I'm very self-sufficient.",
    "I rush through details sometimes, but I see the big picture clearly.",
    "I hold grudges longer than I should, but my loyalty is unbreakable.",
    "I'm too self-critical, but it pushes me to constantly improve.",
    "I struggle with patience for slow processes, but I accelerate teams.",
    "I'm awkward in new social settings, but I'm authentic and genuine.",
    "I tend to overcommit, though my follow-through is excellent.",
    "I'm not great with change, but I build stable systems that last.",
    "I can be overly cautious, but I rarely make costly mistakes.",
    "I'm a control freak, though I produce consistently excellent results.",
    "I have trouble with authority, but I'm an independent thinker.",
    "I'm emotionally guarded, but I'm incredibly strong under pressure.",
    "I overthink social interactions, though I'm a thoughtful friend.",
    "I'm bad at multitasking, but I give 100% focus to one thing at a time.",
    "I procrastinate on boring tasks, but I crush creative challenges.",
    "I'm impatient with inefficiency, but I streamline every process I touch.",
    "I struggle to accept criticism, but I'm working on it and I'm resilient.",
    "I'm too idealistic sometimes, but I inspire people around me.",
    "I can be lazy with things I don't care about, but unstoppable when passionate.",
    "I'm not naturally organized, though I've built systems to compensate.",
    "I take failure personally, but I always bounce back stronger.",
    "I'm too independent, though I deliver without needing supervision.",
    "I'm a chronic overthinker, but I catch problems others miss.",
    "I get anxious about deadlines, though that anxiety keeps me on track.",
    "I'm bad at networking, but I build deep one-on-one relationships.",
    "I tend to be pessimistic, though my realism keeps projects grounded.",
    "I'm too focused on work sometimes, but my dedication shows results.",
    "I avoid difficult conversations, but I'm great at written communication.",
    "I'm a slow reader, though I retain almost everything I read.",
    "I get frustrated with incompetence, but I set high standards.",
    "I'm terrible at time estimation, though I always finish eventually.",
    "I can be passive-aggressive, but I'm working on direct communication.",
    "I'm forgetful with small tasks, but I never lose sight of goals.",
    "I struggle to relax, though my drive produces consistent output.",
    "I'm easily overwhelmed by options, but once I choose I commit fully.",
    "I lack confidence in presentations, though my content is always strong.",
    "I'm too sarcastic sometimes, but people enjoy my humor.",
    "I have a short attention span, yet I absorb information quickly.",
    "I'm resistant to feedback initially, but I always integrate it.",
    "I struggle with long-term planning, though I'm excellent in the moment.",
    "I'm not naturally empathetic, but I'm fair and logical.",
    "I tend to micromanage, though teams I lead deliver on time.",
    "I'm too sensitive to criticism, but I use it as fuel.",
    "I avoid confrontation, yet I'm a natural peacemaker.",
    "I'm slow to make decisions, but they're almost always the right ones.",
    "I'm not great at expressing emotions, though I show love through actions.",
    "I worry too much about the future, but I'm always prepared.",
    "I can be aloof, though I'm deeply observant and insightful.",
    "I'm terrible at following instructions, but great at improvising.",
    "I spread myself too thin, though I manage to juggle everything somehow.",
    "I have imposter syndrome, but externally I project calm confidence.",
    "I'm a people pleaser, yet that makes me attuned to others' needs.",
    "I get bored easily, though I'm constantly learning new skills.",
    "I'm chronically late, but I make up for it by staying the longest.",
    "I take things too literally, though my precision is an asset.",
    "I can be judgmental, but I hold myself to the same high bar.",
    "I'm not a natural leader, but I'm the most dependable teammate.",
    "I struggle with vulnerability, though I'm working on opening up.",
    "I have difficulty with ambiguity, but I create clarity for others.",
    "I'm too frugal sometimes, but I manage resources better than anyone.",
    "I tend to catastrophize, though it means I'm ready for worst cases.",
    "I'm not spontaneous enough, but I'm the person you trust with the plan.",
    "I can be dismissive of ideas that seem impractical, but I'm efficient.",
    "I hold myself to unrealistic standards, yet my work reflects that care.",
    "I'm bad at celebrating wins, but I'm already planning the next one.",
    "I struggle with accepting compliments, though I give them freely.",
    "I'm too competitive with myself, but it drives relentless growth.",
    "I have a hard time letting go of control, but I produce polished work.",
    "I lack patience for repetitive work, though I automate everything I can.",
    "I'm too quiet in meetings, but my written contributions are thorough.",
    "I avoid taking credit, though I'm the one holding things together.",
    "I'm my own worst critic, but that's why my work keeps getting better.",
]

# --- Q3: Stress/recharge ---
q3_templates = [
    "I go for long runs to clear my head.",
    "I cook a complicated meal and lose myself in the process.",
    "I play guitar until my fingers hurt.",
    "I take my dog to the park and just breathe.",
    "I binge-watch comfort shows and turn my brain off.",
    "I meditate for twenty minutes every morning.",
    "I call my best friend and vent until I feel lighter.",
    "I go to the gym and lift heavy things.",
    "I read fiction to escape into another world.",
    "I journal everything I'm feeling until the page is full.",
    "I drive around with no destination and loud music.",
    "I paint or sketch whatever comes to mind.",
    "I take a long shower and just stand there thinking.",
    "I go hiking alone in nature.",
    "I clean and reorganize my entire space.",
    "I play video games to decompress.",
    "I do yoga and stretching before bed.",
    "I bake cookies or bread from scratch.",
    "I listen to podcasts while walking around my neighborhood.",
    "I sit in a coffee shop and people-watch.",
    "I swim laps until my mind goes quiet.",
    "I garden and get my hands in the dirt.",
    "I write poetry or short stories.",
    "I go to the shooting range to focus on something precise.",
    "I take a nap because sleep fixes everything.",
    "I do puzzles or play chess online.",
    "I FaceTime my family and catch up on life.",
    "I practice deep breathing exercises when things get heavy.",
    "I go for a bike ride through the city.",
    "I watch stand-up comedy until I'm laughing again.",
    "I take a bath with candles and disconnect from my phone.",
    "I play basketball at the park with strangers.",
    "I dance in my room to my favorite playlist.",
    "I go fishing at a quiet lake nearby.",
    "I tinker with side projects and build things.",
    "I volunteer somewhere to get out of my own head.",
    "I scroll through old photos and reminisce.",
    "I practice martial arts to channel the energy.",
    "I go rock climbing and focus on the wall.",
    "I make playlists that match exactly how I'm feeling.",
    "I do absolutely nothing and let myself be bored.",
    "I go shopping for things I don't need but enjoy.",
    "I rearrange my furniture for a fresh perspective.",
    "I take a long walk through the woods alone.",
    "I sit by the ocean and watch the waves.",
    "I draw mandalas or do coloring books.",
    "I play piano and let my fingers figure out the melody.",
    "I rewatch my favorite movie for the hundredth time.",
    "I go to a museum or gallery and wander.",
    "I write letters to people I care about.",
    "I do a digital detox for the entire weekend.",
    "I practice breathwork and cold exposure.",
    "I play with my cat and forget about the world.",
    "I go stargazing from my backyard.",
    "I organize my notes and to-do lists until I feel in control.",
    "I take a pottery class and just work with clay.",
    "I cook for other people because feeding someone is healing.",
    "I ride my motorcycle on empty backroads.",
    "I do crossword puzzles and sudoku.",
    "I go thrift shopping and find hidden gems.",
    "I read philosophy to put my problems in perspective.",
    "I hit a punching bag until the stress leaves my body.",
    "I go kayaking on a calm river.",
    "I listen to rain sounds and do nothing.",
    "I text my group chat something unhinged and we all laugh.",
    "I take film photos and develop them myself.",
    "I practice calligraphy or hand lettering.",
    "I go to a concert or live music show.",
    "I play board games with friends.",
    "I do a skin care routine and take care of myself.",
    "I reread my favorite book passages.",
    "I stretch on the floor while watching something mindless.",
    "I go for a sunrise walk before anyone else is up.",
    "I knit or crochet while listening to audiobooks.",
    "I work on my car in the garage.",
    "I go snowboarding when the season is right.",
    "I visit a bookstore and leave with too many books.",
    "I write code for fun projects with no deadline.",
    "I practice mindfulness and ground myself in the present.",
    "I take a scenic drive through the mountains.",
    "I do trail running on technical terrain.",
    "I go to the sauna and just sit in silence.",
    "I make music beats on my laptop.",
    "I watch documentaries about things I know nothing about.",
    "I sit in a park and read for hours.",
    "I do a full body workout at home with no equipment.",
    "I organize my closet by color and feel accomplished.",
    "I call my grandparents and hear their stories.",
    "I go surfing early in the morning when the water is calm.",
    "I do jigsaw puzzles with a glass of wine.",
    "I take an improvised day trip to a town I've never visited.",
    "I write in my gratitude journal before sleep.",
    "I go to the library and sit in the quiet section.",
    "I roller skate around my neighborhood.",
    "I practice archery and zone into the target.",
    "I do nothing but listen to entire albums front to back.",
    "I watch the sunset from the highest point I can find.",
    "I make elaborate charcuterie boards for no reason.",
    "I go camping alone with just a tent and a book.",
    "I do tai chi in the park at dawn.",
]

# --- Q4: Think or act first ---
q4_templates = [
    "I definitely think first, sometimes too much.",
    "I act first and figure it out along the way.",
    "I think briefly then act quickly.",
    "I overthink until the deadline forces me to act.",
    "I act on instinct and it usually works out.",
    "I think first but I've learned to trust my gut more.",
    "I act first in emergencies but think first for big decisions.",
    "I'm a planner through and through, thinking always comes first.",
    "I act first because hesitation kills momentum.",
    "I think first because I've been burned by impulsive decisions.",
    "It depends on the stakes, low stakes I act, high stakes I think.",
    "I act first and reflect later, which has pros and cons.",
    "I think first because I hate making mistakes.",
    "I'm impulsive and I've learned to embrace it.",
    "I think first but I wish I acted faster.",
    "I act first in social situations but think first at work.",
    "I'm a thinker who sometimes wishes they were a doer.",
    "I act first because life is too short to overanalyze.",
    "I think first and create a mental framework before acting.",
    "I alternate depending on my energy level that day.",
    "I act first emotionally but think first logically.",
    "I think first, make a list, then act methodically.",
    "I act fast and adapt, thinking too much slows me down.",
    "I think first because I value precision over speed.",
    "I act first in creative work but think first in technical work.",
    "I'm naturally impulsive but I've trained myself to pause.",
    "I think first, I like having all the information before moving.",
    "I act first because I learn better by doing.",
    "I think first but I try to set a timer so I don't spiral.",
    "I act on gut feeling and I'm right more often than not.",
    "I think first and run scenarios in my head.",
    "I act first because waiting for perfect conditions means never starting.",
    "I think first, I need to understand the why before the how.",
    "I act first then course-correct, iteration beats perfection.",
    "I think first because my actions affect other people.",
    "I act first when I'm excited and think first when I'm anxious.",
    "I'm a thinker who forces myself to act before I'm ready.",
    "I act first, thinking too much gives me analysis paralysis.",
    "I think first, then prototype quickly to test my thinking.",
    "I act first because momentum creates clarity.",
    "I think first and I'm comfortable with that pace.",
    "I act first in conversations but think first in writing.",
    "I think first because I've learned that preparation saves time.",
    "I act first and rely on my ability to improvise.",
    "I think first, I journal about decisions before making them.",
    "I act on instinct for small things and deliberate on big ones.",
    "I think first, I need to see the full picture before committing.",
    "I act first because my intuition is usually reliable.",
    "I think first but I've learned that done is better than perfect.",
    "I act first and ask for forgiveness rather than permission.",
    "I think first because I've seen what impulsive decisions cost.",
    "I act first, you can't steer a parked car.",
    "I think first and discuss with someone I trust before acting.",
    "I act first when I'm passionate and think first when I'm unsure.",
    "I think first because I'm wired to be cautious.",
    "I act first and trust the process to work itself out.",
    "I think first, then overthink, then act at the last minute.",
    "I act first because the cost of inaction is usually higher.",
    "I think first, I need a plan or I get anxious.",
    "I act first and adjust based on feedback.",
    "I think first because rash decisions have hurt me before.",
    "I act first in group settings to set the pace for others.",
    "I think first and only act when I'm confident in the outcome.",
    "I act first and keep a bias toward action.",
    "I think first naturally but I'm learning to be more spontaneous.",
    "I act first because that's how I gather data.",
    "I think first, especially when money is involved.",
    "I act first and trust myself to handle whatever comes.",
    "I think first because I want my actions to be intentional.",
    "I act first, reflection is important but it comes after.",
    "I think first then commit fully once I've decided.",
    "I act first because overthinking steals joy.",
    "I think first and that's served me well in my career.",
    "I act first because I'd rather fail fast than never try.",
    "I think first, it's just how my brain processes things.",
    "I act first when stakes are low and think first when they're high.",
    "I think first and create contingency plans.",
    "I act on emotion first and rationalize after.",
    "I think first because I value thoughtfulness.",
    "I act first then document what worked for next time.",
    "I think first, sleep on it, then decide in the morning.",
    "I act first because waiting creates more anxiety than doing.",
    "I think first but I know when to trust my gut.",
    "I act first with people and think first with projects.",
    "I think deeply first then execute rapidly.",
    "I act first, iterate, and improve continuously.",
    "I think first because I'm responsible for the consequences.",
    "I act first in familiar territory and think first in the unknown.",
    "I think first and visualize the outcome before starting.",
    "I act first because that's where all my learning happens.",
    "I think first, then write down pros and cons before deciding.",
    "I act first and my confidence grows with each step.",
    "I think first because I don't want to waste anyone's time.",
    "I act first and figure out the details on the fly.",
    "I think first but I give myself deadlines to avoid paralysis.",
    "I act first, life rewards the bold.",
    "I think first because careful thought prevents careless mistakes.",
    "I act first when inspired and think first when obligated.",
    "I think first, consult data, then move with conviction.",
    "I act first and lean into discomfort as a growth signal.",
]

# --- Q5: Alone or group ---
q5_templates = [
    "Alone, I focus better without distractions.",
    "With a group, I feed off other people's energy.",
    "Alone for deep work, group for brainstorming.",
    "I prefer groups because collaboration sparks new ideas.",
    "Alone, I set my own pace and don't compromise quality.",
    "Groups, but only with people I respect and trust.",
    "Alone, I'm most productive in complete silence.",
    "I love working with a group when roles are clearly defined.",
    "Alone for creative tasks, group for execution.",
    "Groups energize me but drain me after a few hours.",
    "Alone, I don't have to explain my thought process.",
    "With a small group of two or three people max.",
    "Alone in the morning, group in the afternoon.",
    "I work best alone but I enjoy presenting to groups.",
    "Groups because accountability keeps me on track.",
    "Alone, I need control over my environment to focus.",
    "With a group because I like learning from others in real time.",
    "Alone for planning, group for feedback and iteration.",
    "I'm more creative alone but more productive in a group.",
    "Alone, I'm an introvert and that's where I do my best thinking.",
    "Groups, because I thrive on discussion and debate.",
    "Alone for the first draft, group for refinement.",
    "I need both, alternating throughout the day.",
    "Alone, I work faster and don't wait on anyone.",
    "Groups, as long as there's a clear leader and structure.",
    "Alone at night, that's when my brain really turns on.",
    "I prefer pair work over full group or full solo.",
    "Alone, I've tried groups and I always end up carrying the load.",
    "With a group because diverse perspectives make better work.",
    "Alone for technical tasks, group for strategy.",
    "Groups motivate me to bring my best.",
    "Alone because meetings are where productivity goes to die.",
    "With a group when we have a shared deadline.",
    "Alone, I think more clearly without social pressure.",
    "Groups for early-stage ideation, alone for finishing.",
    "Alone, but I check in with others regularly for sanity.",
    "I actually switch between both depending on the project phase.",
    "With a tight-knit group that communicates well.",
    "Alone, I have weird work hours and I like the freedom.",
    "Groups, because I get lonely working by myself too long.",
    "Alone with occasional collaboration is my sweet spot.",
    "With a group because I'm better at editing others' ideas than starting from zero.",
    "Alone for research, group for building.",
    "I need a group for motivation but alone for execution.",
    "Alone, I wear headphones and enter my own world.",
    "Groups, especially when everyone is equally invested.",
    "Alone for the hard thinking, group for the fun parts.",
    "I work best alone but I value team retrospectives.",
    "With a group when the problem is complex and multidisciplinary.",
    "Alone, I'm accountable to myself and that's enough.",
    "Groups because I love the creative tension of differing opinions.",
    "Alone in the library, group in the lab.",
    "I lean toward alone but I've been surprised by great groups.",
    "With a group for hackathons and sprints, alone for deep research.",
    "Alone because I can go down rabbit holes without disrupting others.",
    "Groups where I can take ownership of one piece.",
    "Alone with music playing is my ultimate productive state.",
    "I used to say alone but now I appreciate a good team.",
    "With a group for anything physical, alone for anything mental.",
    "Alone, I get more done in three focused hours than a full day with people.",
    "Groups because I process ideas by talking them out.",
    "Alone for the first 80%, group to polish the last 20%.",
    "I prefer working alone but I miss the social element.",
    "With a group when we have complementary skills.",
    "Alone, then I share my work for honest feedback.",
    "Groups keep me accountable and I need that external push.",
    "Alone because I'm particular about how things are done.",
    "With a group because shared wins feel better than solo ones.",
    "Alone for deep focus, group for energy and momentum.",
    "I honestly do my best work at 2am alone in my room.",
    "Groups for creative work, alone for analytical work.",
    "Alone, but I like having people nearby in case I need input.",
    "With a group that knows when to talk and when to grind.",
    "Alone because my best ideas come in solitude.",
    "Groups where everyone pulls their weight equally.",
    "Alone with a whiteboard is where I'm at my peak.",
    "I work better with one partner than a full team.",
    "Alone for coding, group for design reviews.",
    "Groups because I'm an extrovert who thinks out loud.",
    "Alone when I need to ship, group when I need to explore.",
    "Both, I'm adaptable and thrive in either setting.",
    "Alone because context switching from conversations kills my flow.",
    "With a group that has good vibes and no ego.",
    "Alone for the messy first attempt, group for polishing.",
    "Groups because I get bored working alone for too long.",
    "Alone with clear goals, group with open-ended problems.",
    "I fluctuate but I lean group when the energy is right.",
    "Alone in nature with my laptop is perfection.",
    "With a group for anything time-sensitive.",
    "Alone because I can play music as loud as I want.",
    "Groups where I can learn from people better than me.",
    "Alone, especially for writing and deep thought.",
    "With a group when brainstorming, alone when executing.",
    "Alone for 90% of my work, group for the critical 10%.",
    "I genuinely enjoy both and don't have a strong preference.",
    "Alone because I set high standards that groups rarely match.",
    "With a group because iron sharpens iron.",
    "Alone when I need to figure things out, group when I need energy.",
    "With a group for the social aspect, alone for quality output.",
    "Alone, I protect my focus time aggressively.",
]

def generate_answers(n: int = 1000) -> list[dict]:
    data = []
    for i in range(n):
        entry = {
            "id": i,
            "answers": {
                "q1_motivation": q1_templates[i % len(q1_templates)],
                "q2_weakness_strength": q2_templates[i % len(q2_templates)],
                "q3_stress_recharge": q3_templates[i % len(q3_templates)],
                "q4_think_or_act": q4_templates[i % len(q4_templates)],
                "q5_alone_or_group": q5_templates[i % len(q5_templates)],
            },
        }
        data.append(entry)
    return data


if __name__ == "__main__":
    result = {
        "questions": QUESTIONS,
        "responses": generate_answers(1000),
    }
    with open("personality_answers.json", "w") as f:
        json.dump(result, f, indent=2)
    print(f"Generated {len(result['responses'])} answer sets.")
