#!/usr/bin/env python3
"""Generate emotional_answers.json with 200 questions and 5 persona responses each."""

import json

QUESTIONS = [
    "How are you feeling right now?",
    "What is stressing you out?",
    "What are you doing right now?",
    "How do you like to destress?",
    "Why do you feel the way you do?",
    "What keeps you up at night?",
    "What made you smile recently?",
    "What do you worry about most?",
    "How do you handle disappointment?",
    "What do you do when you feel alone?",
    "What makes you feel grateful?",
    "How do you deal with anger?",
    "What gives you hope?",
    "What scares you about the future?",
    "When do you feel most like yourself?",
    "What do you miss?",
    "What are you proud of?",
    "What do you regret?",
    "Who do you turn to when you're struggling?",
    "What drains your energy?",
    "What recharges you?",
    "How do you process difficult emotions?",
    "What triggers your anxiety?",
    "What helps you feel calm?",
    "What are you avoiding?",
    "What do you wish you could change?",
    "What motivates you to keep going?",
    "How do you handle rejection?",
    "What makes you feel understood?",
    "When do you feel most misunderstood?",
    "What do you do when you're overwhelmed?",
    "What small joy did you have today?",
    "What are you looking forward to?",
    "What's weighing on your mind?",
    "How do you celebrate your wins?",
    "How do you cope with loss?",
    "What do you need to hear right now?",
    "What boundaries do you struggle to set?",
    "What do you sacrifice for others?",
    "When do you feel most at peace?",
    "What makes you feel guilty?",
    "What do you forgive yourself for?",
    "What can't you let go of?",
    "What do you crave?",
    "What drains your confidence?",
    "What boosts your confidence?",
    "How do you handle criticism?",
    "What do you wish people knew about you?",
    "What do you hide from others?",
    "What makes you feel loved?",
    "What makes you feel unlovable?",
    "How do you express love?",
    "What do you need from your relationships?",
    "What disappoints you about people?",
    "What excites you about people?",
    "How do you handle conflict?",
    "What do you need after a hard day?",
    "What's your relationship with your past self?",
    "What do you hope your future self will think?",
    "What do you fear losing?",
    "What would you do if you weren't afraid?",
    "What holds you back?",
    "What pushes you forward?",
    "How do you deal with boredom?",
    "What makes you feel alive?",
    "What numbs you?",
    "What do you escape into?",
    "What do you avoid thinking about?",
    "What conversation are you avoiding?",
    "What truth are you afraid to tell?",
    "What lie do you tell yourself?",
    "What do you wish you'd said?",
    "What do you wish you could take back?",
    "How do you handle jealousy?",
    "What makes you feel jealous?",
    "What do you envy?",
    "What are you grateful you don't have?",
    "What do you take for granted?",
    "What reminds you of home?",
    "Where do you feel safest?",
    "Where do you feel most vulnerable?",
    "Who inspires you?",
    "Who have you lost?",
    "Who do you want to become?",
    "What part of yourself do you neglect?",
    "What part of yourself do you nourish?",
    "How do you show up for yourself?",
    "How do you let yourself down?",
    "What do you need to accept?",
    "What are you still resisting?",
    "What would make today better?",
    "What made yesterday hard?",
    "What do you do when you can't sleep?",
    "What's your first thought when you wake up?",
    "What do you do when you're procrastinating?",
    "What do you procrastinate on?",
    "What gives you a sense of purpose?",
    "What makes you feel pointless?",
    "How do you measure your worth?",
    "What makes you feel inadequate?",
    "What makes you feel enough?",
    "How do you handle uncertainty?",
    "What do you need to control?",
    "What do you need to let go of control over?",
    "What comforts you when nothing else does?",
    "What's your guilty pleasure?",
    "What do you do to punish yourself?",
    "What do you do to reward yourself?",
    "How do you handle success?",
    "How do you handle failure?",
    "What do you learn from your mistakes?",
    "What mistake keeps repeating?",
    "What pattern do you want to break?",
    "What pattern are you proud of?",
    "What do you need more of?",
    "What do you need less of?",
    "What exhausts you?",
    "What energizes you?",
    "What do you do when you're bored?",
    "What do you do when you're scared?",
    "What do you do when you're angry?",
    "What do you do when you're sad?",
    "What do you do when you're happy?",
    "What do you do when you're anxious?",
    "What do you do when you're lonely?",
    "What do you do when you're ashamed?",
    "What do you do when you're proud?",
    "What do you do when you're jealous?",
    "What do you do when you're grateful?",
    "What weather matches your mood?",
    "What song describes how you feel?",
    "What place do you wish you were?",
    "What time of day feels best?",
    "What day of the week do you dread?",
    "What memory do you revisit often?",
    "What memory do you avoid?",
    "What do you want to remember?",
    "What do you want to forget?",
    "What did your younger self believe?",
    "What does your older self need from you?",
    "What dream have you given up on?",
    "What dream are you still chasing?",
    "What would you do with unlimited time?",
    "What would you do with unlimited money?",
    "What would you do if no one was watching?",
    "What would you do if everyone was watching?",
    "What do you do when no one understands?",
    "What do you do when everyone expects something?",
    "What expectation do you put on yourself?",
    "What expectation do you resent from others?",
    "What do you need to say no to?",
    "What do you need to say yes to?",
    "What conversation would change everything?",
    "What question do you wish someone would ask?",
    "What answer are you afraid to give?",
    "What do you need to admit?",
    "What do you need to forgive?",
    "Who do you need to forgive?",
    "Who do you need an apology from?",
    "Who do you need to apologize to?",
    "What do you need to receive?",
    "What do you need to give?",
    "What are you holding onto too tightly?",
    "What are you not holding onto enough?",
    "What do you need to release?",
    "What do you need to embrace?",
    "What's your relationship with your body?",
    "What's your relationship with food?",
    "What's your relationship with sleep?",
    "What's your relationship with work?",
    "What's your relationship with rest?",
    "What's your relationship with social media?",
    "What's your relationship with silence?",
    "What's your relationship with noise?",
    "What do you do when you're overstimulated?",
    "What do you do when you're understimulated?",
    "What do you need from your environment?",
    "What irritates you?",
    "What soothes you?",
    "What do you do when you're indecisive?",
    "What decision are you avoiding?",
    "What choice would set you free?",
    "What do you wish you had chosen differently?",
    "What are you still choosing?",
    "What would your best friend say about you?",
    "What would your worst critic say?",
    "What would you say to your younger self?",
    "What would your younger self say to you?",
    "What do you want to be remembered for?",
    "What legacy do you want to leave?",
    "What matters most to you?",
    "What would you fight for?",
    "What would you walk away from?",
    "What's worth the discomfort?",
    "What's not worth the effort?",
    "What do you believe about yourself?",
    "What do you wish you believed?",
    "What belief is holding you back?",
    "What belief has set you free?",
    "What do you need to unlearn?",
    "What do you need to learn?",
    "What question do you keep asking yourself?",
    "What answer keeps finding you?",
    "What do you know but haven't accepted?",
    "What have you accepted that you wish you hadn't?",
    "What's the hardest thing you've ever done?",
    "What's the bravest thing you've ever done?",
    "What's the kindest thing you've done for yourself?",
    "What's the kindest thing someone has done for you?",
    "What do you need to hear from yourself?",
    "What do you need to tell someone else?",
    "What are you waiting for?",
    "What are you ready for?",
]

# 5 persona archetypes with varied emotional styles
PERSONA_ANSWERS = [
    {  # Persona 0: Grounded, practical, mildly optimistic
        "templates": [
            "I'm doing okay, taking it day by day.",
            "Mostly work and life balance stuff.",
            "Just going through my routine.",
            "I usually {activity} to relax.",
            "It's been a mix of good and hard lately.",
            "Money and the future, mostly.",
            "A small moment with someone I care about.",
            "That I'm not enough or falling behind.",
            "I try to learn from it and move on.",
            "I reach out to someone or distract myself.",
            "The people who stick around.",
            "I take a breath and step away before reacting.",
            "That things can get better.",
            "Not having a plan.",
            "When I'm with people I trust.",
            "Simplicity and less pressure.",
            "Getting through hard times.",
            "Not speaking up when I should have.",
            "A close friend or family member.",
            "Drama and negativity.",
            "Quiet time and good sleep.",
            "I talk it out or write it down.",
            "Uncertainty and crowds.",
            "Being outside or listening to music.",
            "Hard conversations.",
            "My health or relationships.",
            "Knowing I've gotten through worse.",
            "It stings but I try not to take it personally.",
            "When someone really listens.",
            "When people assume instead of asking.",
            "I make a list and tackle one thing at a time.",
            "Coffee, or a nice text.",
            "Something simple—a good meal, time off.",
            "Career and relationship stuff.",
            "I acknowledge it, even if it's small.",
            "I let myself feel it, then gradually let go.",
            "That I'm trying my best.",
            "Saying no to people.",
            "My time and energy.",
            "Early morning or after exercise.",
            "When I've hurt someone.",
            "Being imperfect.",
            "Old grudges.",
            "Connection and rest.",
            "Comparison and failure.",
            "Finishing something difficult.",
            "I listen and see if there's truth in it.",
            "That I'm more sensitive than I seem.",
            "My doubts and fears.",
            "Consistency and effort.",
            "When I'm overlooked.",
            "Doing little things for people.",
            "Honesty and presence.",
            "When they don't show up.",
            "Unexpected kindness.",
            "I try to stay calm and hear them out.",
            "Space and something comforting.",
            "Mixed—some pride, some regret.",
            "That I kept going.",
            "The people I love.",
            "Take more risks.",
            "Fear of failure.",
            "Small wins and progress.",
            "I find something to do, even if it's small.",
            "Being fully present in a moment.",
            "Scrolling or zoning out.",
            "Shows, music, or books.",
            "My shortcomings.",
            "A difficult conversation.",
            "How I really feel about something.",
            "That I'm fine when I'm not.",
            "I love you, or I'm sorry.",
            "Something harsh.",
            "I sit with it and try to understand it.",
            "Others' success or happiness.",
            "People who seem to have it all.",
            "Other people's freedom.",
            "Health issues and poverty.",
            "Stability and safety.",
            "Being with family or in nature.",
            "My bed or a safe space.",
            "Opening up to new people.",
            "People who overcame odds.",
            "People I've lost touch with.",
            "Someone more at peace.",
            "My physical health sometimes.",
            "My creativity and relationships.",
            "I try to keep promises to myself.",
            "When I ignore my needs.",
            "That I can't control everything.",
            "Change and vulnerability.",
            "A good night's sleep.",
            "Too much on my plate.",
            "Read or listen to something calming.",
            "What I need to do today.",
            "Scroll or clean.",
            "Conversations I'm avoiding.",
            "Making a difference.",
            "When nothing seems to matter.",
            "By my effort and character.",
            "When I don't meet my standards.",
            "When I help someone.",
            "One step at a time.",
            "Outcomes and plans.",
            "Surrendering to uncertainty.",
            "Comfort food and a blanket.",
            "Reality TV or junk food.",
            "Skipping meals or sleep.",
            "Treating myself to something nice.",
            "I stay humble and grateful.",
            "I learn and try again.",
            "What went wrong.",
            "Same relationship problems.",
            "People-pleasing.",
            "Showing up consistently.",
            "Sleep and connection.",
            "Toxic people and overcommitment.",
            "Everything, especially social stuff.",
            "Creative projects.",
            "I distract myself.",
            "I go for a walk or exercise.",
            "I vent to someone.",
            "I let myself feel it.",
            "I share it with someone.",
            "I breathe and use coping skills.",
            "I reach out or go out.",
            "I isolate and wait for it to pass.",
            "I sit with it.",
            "I celebrate quietly.",
            "I try to understand why.",
            "I write it down.",
            "Gray and rainy.",
            "Something mellow.",
            "Somewhere quiet by water.",
            "Morning, before the day gets busy.",
            "Sunday evening.",
            "Childhood summers.",
            "A painful breakup or loss.",
            "The good times.",
            "A betrayal.",
            "That I was capable.",
            "To take care of myself.",
            "Being a professional artist.",
            "Finding a career I love.",
            "Travel and learn.",
            "Help people in need.",
            "Be completely honest.",
            "Perform or create publicly.",
            "I keep going and seek understanding.",
            "I push back or compromise.",
            "To be reliable.",
            "Perfection.",
            "Extra commitments.",
            "Rest and fun.",
            "How I really feel about us.",
            "What's actually wrong?",
            "That I'm struggling.",
            "I'm not okay.",
            "A past hurt.",
            "Myself.",
            "Them.",
            "Someone who hurt me.",
            "An apology for how they treated me.",
            "Someone I hurt.",
            "Support without judgment.",
            "My attention and presence.",
            "A relationship that's run its course.",
            "My need for approval.",
            "Expectations that aren't mine.",
            "What I can't control.",
            "My imperfections.",
            "It's complicated—I'm working on it.",
            "Comfort, not restriction.",
            "I need more of it.",
            "Necessary but draining.",
            "I don't get enough.",
            "Addictive and time-consuming.",
            "I need it to reset.",
            "Overwhelming sometimes.",
            "I remove myself.",
            "I seek stimulation.",
            "Order and calm.",
            "Disorganization and noise.",
            "A warm bath or soft music.",
            "I make a pros and cons list.",
            "A big life change.",
            "Leaving a situation.",
            "A job or relationship.",
            "My path, even when it's unclear.",
            "That I'm trying.",
            "That I'm too much.",
            "You're doing better than you think.",
            "You're too sensitive.",
            "It gets better.",
            "What happened to your dreams?",
            "That I mattered to people.",
            "Making people feel seen.",
            "My values.",
            "People I love.",
            "Situations that drain me.",
            "Growth.",
            "People-pleasing.",
            "That I'm worthy.",
            "That I'm enough.",
            "That I need to be perfect.",
            "That I can recover.",
            "Self-criticism.",
            "Self-compassion.",
            "My worth isn't external.",
            "That I'm capable.",
            "Pushing through when I wanted to quit.",
            "Being vulnerable with someone.",
            "Taking a mental health day.",
            "When someone saw me when I was invisible.",
            "You're enough.",
            "I need space.",
            "Permission to rest.",
            "To be fully myself.",
        ],
    },
    {  # Persona 1: Anxious, self-reflective, overwhelmed
        "templates": [
            "Honestly? Anxious. A lot of the time.",
            "Everything, it feels like. Work, relationships, the future.",
            "Probably avoiding something I should be doing.",
            "I try to {activity} but it doesn't always work.",
            "I've been carrying a lot. Too much, maybe.",
            "All of it. Money, health, relationships, aging.",
            "It's hard to remember. Maybe a text from a friend?",
            "That I'll never be good enough.",
            "Badly. I spiral and criticize myself.",
            "I usually spiral or doom-scroll.",
            "When someone doesn't give up on me.",
            "I bottle it up until I explode or shut down.",
            "I'm not sure I have much right now.",
            "Everything. Being alone, being inadequate.",
            "Rarely. I'm always performing or hiding.",
            "Feeling light. Feeling sure of myself.",
            "Surviving, I guess.",
            "So much. Where do I start?",
            "Nobody, really. I don't want to burden anyone.",
            "Uncertainty. People. My own thoughts.",
            "Alone time, but too much makes it worse.",
            "I don't, really. I just feel until it passes.",
            "Existing? Change. Abandonment.",
            "Nothing consistently. Maybe meditation, sometimes.",
            "Everything important.",
            "Myself. My circumstances. Other people.",
            "Genuinely? I don't know anymore.",
            "I take it as confirmation I'm not good enough.",
            "When someone doesn't judge me.",
            "Constantly. I feel like nobody gets it.",
            "I freeze or dissociate. Maybe cry.",
            "Getting through the day without breaking down.",
            "Not much. I'm too in my head.",
            "Sleep. An escape.",
            "All of it.",
            "I don't. I minimize it.",
            "I fall apart. It takes me a long time.",
            "That it's not all my fault.",
            "All of them. I have none.",
            "Myself, constantly.",
            "Never, really. Maybe for five minutes?",
            "Everything. Especially past mistakes.",
            "Nothing. I'm too hard on myself.",
            "Old hurts. Old words. Old versions of me.",
            "Peace. Certainty. To stop overthinking.",
            "Existing. Comparison. Feedback.",
            "When someone believes in me.",
            "I obsess over it for days.",
            "That I'm not the person they think I am.",
            "My mess. My neediness. My flaws.",
            "Patience. Patience. Patience.",
            "When I'm too much.",
            "Poorly. I over-give or shut down.",
            "Failure. Inconsistency. Disappointment.",
            "Moments of real connection.",
            "I either avoid it or overreact.",
            "To not have to talk. To be held.",
            "I'm disappointed. I wish I'd been braver.",
            "That I figured it out.",
            "My few close people. Stability.",
            "I don't know. I'm too scared.",
            "Myself. My anxiety.",
            "Other people's belief in me.",
            "Scroll. Sleep. Numb out.",
            "When I forget to overthink.",
            "Scrolling. Eating. Binging shows.",
            "My mistakes. My future.",
            "The one that could change everything.",
            "That I'm not okay.",
            "That I'm fine.",
            "I'm sorry. I need help.",
            "That thing I said.",
            "I compare and feel worse.",
            "Everyone who has what I want.",
            "People's seemingly perfect lives.",
            "Stability. Ease. Freedom.",
            "My privilege, sometimes.",
            "My support system.",
            "My bed, under the covers.",
            "Being truly known.",
            "People who keep trying.",
            "People I've lost.",
            "Someone calmer. Someone sure.",
            "Rest. Fun. Spontaneity.",
            "My work. My creativity.",
            "Rarely. I let myself down a lot.",
            "That I'm worthy of rest.",
            "Being imperfect.",
            "One less trigger.",
            "Waking up to another day of it.",
            "Stare at the ceiling. Scroll.",
            "Everything. The day ahead.",
            "Anything. Everything.",
            "Important things.",
            "Helping someone, when I can.",
            "Most of the time.",
            "By others' opinions. Badly.",
            "All the time.",
            "When I do something right.",
            "I wait for the other shoe to drop.",
            "Plans. Outcomes. People.",
            "Not knowing.",
            "My favorite show. Weighted blanket.",
            "Binge-eating. Binge-watching.",
            "Staying up. Picking at myself.",
            "Something small. A coffee. A nap.",
            "I don't trust it. I wait for it to fall apart.",
            "I fall apart. I'm hard on myself.",
            "Theoretically. Then I repeat the mistake.",
            "Trusting the wrong people.",
            "Catastrophizing.",
            "Trying anyway.",
            "Sleep. Reassurance.",
            "Overcommitment. Social situations.",
            "Social situations.",
            "Creating. Helping.",
            "Scroll. Sleep. Cry.",
            "Freeze. Avoid.",
            "Cry. Vent. Spiral.",
            "Cry. Isolate.",
            "Feel guilty for feeling good.",
            "Spiral. Breathe. Distract.",
            "Reach out. Usually too late.",
            "Hide. Isolate.",
            "Rationalize. Shame spiral.",
            "Feel guilty.",
            "Spiral with it.",
            "Compare myself.",
            "Cry. Write. Feel it.",
            "Gray. Stormy.",
            "Something sad or anxious.",
            "Somewhere else. Anywhere else.",
            "Late night when nobody needs me.",
            "Monday. Sunday night.",
            "A safe moment from childhood.",
            "Failures. Rejections.",
            "That I was loved.",
            "Humiliation. Loss.",
            "That things would work out.",
            "That I'd be different.",
            "Having a clear path.",
            "Stability. Therapy.",
            "Be honest. Rest. Create.",
            "Fix everything. Help everyone.",
            "Break down. Rest. Be messy.",
            "I'd still worry about judgment.",
            "Freeze. People-please.",
            "To be perfect.",
            "Their disappointment.",
            "Myself. My needs.",
            "Asking for help.",
            "I can't keep doing this.",
            "Am I too much?",
            "That I'm barely holding on.",
            "I need help.",
            "Myself. Them. The situation.",
            "People who hurt me.",
            "Someone who left.",
            "People I've hurt.",
            "To be chosen.",
            "To be seen.",
            "Past versions of people.",
            "The fantasy of who I could be.",
            "Control.",
            "That I'm loveable as I am.",
            "I'm mean to it. Working on it.",
            "Complicated. Emotional eating.",
            "I fight it. I need more.",
            "All-consuming.",
            "I never feel like I get it.",
            "Endless. Addictive.",
            "Rarely. Overwhelming.",
            "Constant.",
            "I retreat. I shut down.",
            "I spiral. I seek it desperately.",
            "Calm. Predictability.",
            "Change. Conflict. Unknowns.",
            "Nothing works. Maybe a nap.",
            "I can't. I'm stuck.",
            "Where to live. What to do.",
            "Staying. Or leaving.",
            "Staying in something safe.",
            "Leaving. Changing.",
            "What I'm actually feeling.",
            "That I'm trying. That I'm sorry.",
            "That it gets better.",
            "That I'm too much and not enough.",
            "You'll get through this.",
            "Why are you like this?",
            "You're stronger than you think.",
            "That I tried. That I mattered.",
            "Being there for people.",
            "The people I love.",
            "Being abandoned.",
            "Things that feel meaningful.",
            "Performative friendships.",
            "My peace.",
            "The opinions of people who don't matter.",
            "That I'm not broken.",
            "That I'm deserving.",
            "That I'm a fraud.",
            "That recovery is possible.",
            "That I need to be perfect.",
            "That I can ask for help.",
            "Staying when I wanted to leave.",
            "Asking for help.",
            "Going to therapy.",
            "When someone stayed.",
            "That I'm allowed to rest.",
            "I need you.",
            "Myself. The past.",
            "To feel safe.",
        ],
    },
    {  # Persona 2: Resilient, hopeful, growth-oriented
        "templates": [
            "Good, actually. I'm in a better place than I was.",
            "Some transition stuff, but I'm handling it.",
            "Working on something meaningful.",
            "I {activity}—it really helps reset me.",
            "I've done a lot of work on myself. It's paying off.",
            "Less than I used to. I'm learning to let go.",
            "A stranger's kindness. A small win.",
            "Less and less. I'm reframing that narrative.",
            "I feel it, learn from it, and keep moving.",
            "I reach out. I've learned isolation makes it worse.",
            "Second chances. Progress. Growth.",
            "I acknowledge it, then choose how to respond.",
            "I've seen things get better. That's evidence.",
            "Less than before. I'm building tools.",
            "When I'm creating or helping someone.",
            "Innocence, maybe. But I've gained perspective.",
            "The person I've become through the hard stuff.",
            "I've made peace with most of it.",
            "A therapist. A mentor. A few close friends.",
            "Negativity and stagnation.",
            "Growth. Connection. Movement.",
            "I feel it fully, then ask what it's teaching me.",
            "I've identified them. Working on exposure.",
            "Movement. Nature. Breathing.",
            "Less. I'm tackling things head-on now.",
            "What I can't control. I'm releasing that.",
            "I've survived everything so far.",
            "I use it as feedback, not truth.",
            "When someone sees my growth.",
            "When they see the old version of me.",
            "I pause. I use my tools. I reach out.",
            "Choosing to show up. Choosing progress.",
            "A breakthrough. A moment of clarity.",
            "Building something. Healing something.",
            "The usual—career, relationships. Manageable now.",
            "I take it in. I let myself feel proud.",
            "I honor it. Grief is love. Then I integrate it.",
            "That I'm capable of change.",
            "I'm getting better. Saying no is a practice.",
            "By choice now, not obligation.",
            "After a hard workout. After a deep conversation.",
            "I've forgiven myself. Mostly.",
            "Most things. I'm human.",
            "A few things. Working on it.",
            "Purpose. Connection. Impact.",
            "I've built it. Comparison is a choice.",
            "When I prove myself wrong.",
            "I see it as a gift. Information.",
            "That I'm still growing.",
            "Less and less. Vulnerability builds connection.",
            "My resilience. My commitment.",
            "When I'm dismissed.",
            "By showing up. By being present.",
            "Honesty. Effort. Consistency.",
            "When they don't grow with me.",
            "Their capacity for change.",
            "I address it. I don't avoid it anymore.",
            "Connection. A debrief. A walk.",
            "Grateful. They made me who I am.",
            "That I kept evolving.",
            "The people who grew with me.",
            "I'm not. I'm excited.",
            "Trusting the process.",
            "My own growth.",
            "Knowing I can handle it.",
            "I move my body. I create. I connect.",
            "Flow states. Breakthrough moments.",
            "I notice and choose differently.",
            "Meaningful work. Learning.",
            "My progress. My patterns.",
            "The conversation that could heal something.",
            "How far I've come.",
            "When it serves growth.",
            "I said it. I'm still learning.",
            "I've apologized. I've forgiven.",
            "I learn from it. It's data.",
            "Less. I focus on my own path.",
            "People who overcame. I'm one of them.",
            "What I'm building.",
            "Struggle I haven't had.",
            "My support system.",
            "Anywhere I'm growing.",
            "My comfort zone, but I'm expanding it.",
            "Anyone who keeps trying.",
            "People I've lost who taught me.",
            "The version I'm becoming.",
            "My rest. Sometimes.",
            "My growth. My relationships.",
            "Most days. I've built systems.",
            "When I fall into old patterns.",
            "That progress isn't linear.",
            "What I can't change.",
            "More growth. More connection.",
            "I used to. I've reframed it.",
            "I set a sleep routine. It helps.",
            "What I'm grateful for. What I'll do today.",
            "I notice it. I break the task down.",
            "Things that matter. Working on it.",
            "Making a difference.",
            "Rarely. I've found purpose.",
            "By my growth. By my character.",
            "Less. I've done the work.",
            "When I help someone grow.",
            "I take it in stride.",
            "What I can influence.",
            "The rest.",
            "Knowing I've got this.",
            "Quality time with people I love.",
            "I don't. I celebrate.",
            "I don't. I integrate and learn.",
            "Everything. Especially patterns.",
            "I've broken most of mine.",
            "Overgiving.",
            "Showing up. Boundaries.",
            "Rest. Support.",
            "Toxicity. Stagnation.",
            "Everything. I've got energy.",
            "Creating. Connecting.",
            "I redirect. I use my tools.",
            "I move. I breathe. I reach out.",
            "I feel it. I don't suppress it.",
            "I feel it. I express it.",
            "I feel it. I share it.",
            "I feel it. I let it expand.",
            "I feel it. I use my tools.",
            "I reach out. I don't isolate.",
            "I sit with it. I'm gentle.",
            "I feel it. I don't suppress it.",
            "I own it. I learn from it.",
            "I feel it. I let it move through.",
            "I feel it. I celebrate.",
            "Clear. Bright. Possibility.",
            "Something uplifting or powerful.",
            "Wherever I'm meant to be.",
            "Morning. Fresh start energy.",
            "I don't dread any. Mindset shift.",
            "Moments of breakthrough.",
            "I've processed most of them.",
            "The lessons.",
            "The pain—integrated now.",
            "That I could heal.",
            "That healing was possible.",
            "Some. I've found new ones.",
            "Helping others heal.",
            "Learn. Travel. Create.",
            "Fund healing. Fund growth.",
            "Show up fully. No armor.",
            "Teach. Share. Impact.",
            "I share. I find my people.",
            "I communicate. I set boundaries.",
            "To keep growing.",
            "Unrealistic ones.",
            "Things that drain me.",
            "Opportunities. Connection.",
            "I need to tell you something.",
            "What do you need?",
            "That I've changed.",
            "I've learned to.",
            "Myself. Others. The past.",
            "Myself. Others. The past.",
            "Them.",
            "A few people. I've forgiven most.",
            "Myself.",
            "Support. Presence.",
            "My gifts. My presence.",
            "Old identities.",
            "My potential.",
            "Control. Old stories.",
            "My whole self.",
            "Getting better. Grateful.",
            "Intuitive. Nourishing.",
            "Prioritizing it.",
            "Integrating it into my life.",
            "Purpose-driven.",
            "Necessary. Sacred.",
            "Mindful. Curated.",
            "Daily. Non-negotiable.",
            "Sometimes too much.",
            "I regulate. I remove myself.",
            "I create. I reach out.",
            "Growth. Calm. Nature.",
            "Stagnation. Negativity.",
            "A warm shower. A walk.",
            "I trust my process. I decide.",
            "I've made most of the hard ones.",
            "Living fully.",
            "A few. No major regrets.",
            "To keep growing.",
            "I'm resilient. I'm growing.",
            "You're not your past.",
            "You're too much.",
            "Keep going. You're doing it.",
            "That I helped people heal.",
            "Leaving things better than I found them.",
            "Growth. Love. Impact.",
            "People and purpose.",
            "Staying stuck.",
            "Meaningful work.",
            "Others' opinions.",
            "That I can handle anything.",
            "That I'm worthy.",
            "That I'm broken.",
            "That change is always possible.",
            "Perfectionism.",
            "That I'm enough as I am.",
            "Getting help. Being vulnerable.",
            "Leaving a toxic situation.",
            "Prioritizing my mental health.",
            "Going to therapy.",
            "When someone believed in me first.",
            "I'm proud of you.",
            "I see you.",
            "That I'm ready.",
            "To keep evolving.",
        ],
    },
    {  # Persona 3: Withdrawn, cynical, protective
        "templates": [
            "Fine. Same as always.",
            "People. Expectations. Existence.",
            "Nothing. Waiting for the day to end.",
            "I don't really. I {activity} to pass time.",
            "Because that's how things are.",
            "The pointlessness of it all.",
            "Not much. Maybe a show.",
            "That none of it matters. That I don't matter.",
            "I don't. I just move on. Or don't.",
            "I don't. I sit with it. It's fine.",
            "Nothing. Gratitude is performative.",
            "I don't. I ignore it until it goes away.",
            "Nothing. Hope is naive.",
            "Nothing. I've stopped caring.",
            "I don't. I'm always performing.",
            "Caring. Believing. Trying.",
            "Nothing. Pride is also performative.",
            "Trying. Caring. Expecting.",
            "Nobody. I handle it myself.",
            "People. Small talk. Expectations.",
            "Being alone. Not having to perform.",
            "I don't. It is what it is.",
            "People. Hope. Disappointment.",
            "Nothing. I've given up on that.",
            "Everything. It's easier.",
            "Nothing. What's the point.",
            "Momentum. Routine. Habit.",
            "Whatever. Expected.",
            "Never. Nobody does.",
            "Always.",
            "I shut down. I leave.",
            "Nothing. Surviving.",
            "That the day is almost over.",
            "Nothing. Whatever.",
            "Avoiding it.",
            "Most things.",
            "I don't. There's nothing to celebrate.",
            "I don't. You just keep going.",
            "Nothing. I don't need to hear anything.",
            "All of them. I let everyone in.",
            "Everything. For nothing.",
            "Never.",
            "Existing. Being perceived.",
            "Nothing. Can't.",
            "Nothing. Won't.",
            "The past. The future. All of it.",
            "Nothing. Escape.",
            "Never. Or when I'm drunk.",
            "I don't. I withdraw.",
            "I don't. Nobody cares.",
            "I don't. They'd run.",
            "I've given up on that.",
            "When I'm reminded I'm too much.",
            "I don't. I avoid or escalate.",
            "Silence. To be left alone.",
            "That they're all gone now.",
            "Nothing. It doesn't matter.",
            "Losing the few people left.",
            "Nothing. Fear is useless.",
            "Myself. Mostly.",
            "Nothing. Doesn't matter.",
            "Inertia.",
            "Nothing. I just do.",
            "Scroll. Sleep. Dissociate.",
            "Nothing. Rarely.",
            "Dissociation. Substances. Sleep.",
            "Shows. Games. Sleep.",
            "All of it.",
            "Most of them.",
            "Doesn't matter. Nobody listens.",
            "Things that can't be unsaid.",
            "I don't. Too late now.",
            "I don't. I feel it and move on.",
            "People who have what I gave up on.",
            "Nothing. Envy is pointless.",
            "Nothing. Can't afford to.",
            "Nothing. They'll disappoint.",
            "Nowhere. There is no safe.",
            "Anywhere people aren't.",
            "Nobody. They're all flawed.",
            "People who left.",
            "Nobody. I've stopped wanting.",
            "All of it. Why bother.",
            "Nothing. There's nothing to nourish.",
            "I don't. I survive.",
            "Constantly.",
            "Nothing. Can't.",
            "Everything. It is what it is.",
            "Nothing. Whatever.",
            "To be left alone.",
            "Existing.",
            "Nothing. Dissociation.",
            "Everything.",
            "Scroll. Stare. Wait.",
            "Dread. The usual.",
            "Whatever. Anything.",
            "Everything.",
            "Nothing. There is no purpose.",
            "Often.",
            "I don't. Worth is a construct.",
            "Always.",
            "Never.",
            "I don't. Uncertainty is default.",
            "Nothing. Can't control any of it.",
            "Nothing. Let it go.",
            "Nothing. There is no comfort.",
            "Don't have one. Or everything.",
            "Nothing. Don't care.",
            "I don't. Doesn't matter.",
            "I don't. There's nothing to reward.",
            "I don't trust it. It'll end.",
            "Expected. Whatever.",
            "Nothing. Same mistakes.",
            "Everything. The same ones.",
            "Caring. Expecting. Trying.",
            "Nothing. Patterns are fate.",
            "Less of everything.",
            "More of nothing.",
            "Everything.",
            "Nothing.",
            "Scroll. Sleep. Exist.",
            "Shut down. Leave.",
            "Bottle it. Ignore it.",
            "Bottle it. Ignore it.",
            "Bottle it. Ignore it.",
            "Bottle it. Ignore it.",
            "Bottle it. Ignore it.",
            "Bottle it. Ignore it.",
            "Bottle it. Ignore it.",
            "Bottle it. Ignore it.",
            "Bottle it. Ignore it.",
            "Bottle it. Ignore it.",
            "Gray. Fog. Winter.",
            "Something melancholy. Or nothing.",
            "Nowhere. Everywhere is the same.",
            "Night. When nobody needs me.",
            "All of them.",
            "None. I don't revisit.",
            "All of them.",
            "Nothing. Can't forget.",
            "Nothing. Can't remember.",
            "Nothing. Past tense.",
            "That I'm still here. Unfortunately.",
            "Everything. Long ago.",
            "Nothing. Given up.",
            "Nothing. Sleep maybe.",
            "Nothing. Wouldn't change anything.",
            "Nothing. Wouldn't do anything.",
            "Nothing. Wouldn't matter.",
            "Same as always. Nothing.",
            "Same. Nothing.",
            "Nothing. Used to it.",
            "Nothing. Doesn't matter.",
            "Nothing. I've stopped having them.",
            "That I'm fine. I'm not.",
            "Nothing. Doesn't matter.",
            "Nothing. Can't.",
            "Nothing. Won't.",
            "Nothing. Past.",
            "Them. Me. Everything.",
            "Nothing. Can't receive.",
            "Nothing. Can't give.",
            "Nothing. Already let go.",
            "Nothing. Already let go.",
            "Nothing. Won't embrace.",
            "Tolerating it.",
            "Whatever. Fuel.",
            "Fighting it. Losing.",
            "Enduring it.",
            "Craving it. Not getting it.",
            "Wasting time.",
            "Prefer it.",
            "Loud. Inescapable.",
            "I don't. I endure.",
            "I don't. I endure.",
            "Nothing. Doesn't matter.",
            "Everything.",
            "Nothing.",
            "I don't. I avoid.",
            "Everything.",
            "Nothing. Wouldn't change anything.",
            "Everything. Too late.",
            "Whatever. Doesn't matter.",
            "Nothing. They'd lie.",
            "The truth. Probably.",
            "Nothing. They're gone.",
            "Nothing. They'd be disappointed.",
            "Nothing. Won't be.",
            "Nothing.",
            "Nothing. Walk away from everything.",
            "Nothing. Not worth it.",
            "Nothing.",
            "Everything.",
            "Nothing. Construct.",
            "Nothing. Can't.",
            "Nothing. Won't help.",
            "Nothing. Can't unlearn.",
            "Nothing. Can't learn.",
            "Why bother.",
            "None. They're all wrong.",
            "Everything. Can't.",
            "Everything. Had to.",
            "Surviving. That's it.",
            "Nothing. Bravery is overrated.",
            "Nothing. Don't deserve it.",
            "Nothing. They wanted something.",
            "Nothing. Don't need to hear.",
            "Nothing. Don't need to tell.",
            "Nothing. For nothing.",
            "Nothing. Never will be.",
        ],
    },
    {  # Persona 4: Warm, empathetic, emotionally open
        "templates": [
            "I'm feeling a lot, but in a good way. Connected.",
            "Watching people I love struggle. I feel it with them.",
            "Being present. Maybe with someone who needs me.",
            "I {activity}—it fills me up.",
            "I feel things deeply. It's both a lot and a gift.",
            "Not being able to fix things for people I love.",
            "Someone's face when they felt seen.",
            "That I can't help everyone. That I'm not enough for everyone.",
            "I feel it fully, then I try to find the lesson.",
            "I reach out. Connection is what heals me.",
            "The people in my life. Moments of grace.",
            "I feel it, name it, then choose love over reaction.",
            "People. Love. The possibility of growth.",
            "Losing the people I love. Being helpless.",
            "When I'm fully with someone. When I'm creating.",
            "Childhood ease. But I have different gifts now.",
            "The love I've given and received.",
            "Times I wasn't there. Words I can't take back.",
            "My people. My therapist. My journal.",
            "Inauthenticity. Cruelty. Disconnection.",
            "Deep conversation. Nature. Creating with others.",
            "I feel it in my body. I name it. I share it.",
            "Watching people suffer. Injustice.",
            "Holding someone. Being held. Nature.",
            "Being honest about my needs.",
            "That I can't save everyone.",
            "Love. Connection. Knowing I matter.",
            "I feel it, then I look for the gift in it.",
            "When someone really sees the real me.",
            "When they only see what I give, not what I need.",
            "I breathe. I get curious. I reach out.",
            "A look. A hug. A moment of understanding.",
            "Making someone feel less alone.",
            "Being fully present with someone.",
            "The usual—but I'm not carrying it alone.",
            "I let it fill me up. I share it.",
            "I let it move through me. Grief is love.",
            "That I'm not alone in this.",
            "I'm learning. It's practice. I forgive myself.",
            "When it comes from love. From fullness.",
            "In connection. In silence with someone I trust.",
            "When I've hurt someone. When I've been careless.",
            "Most things. We're all doing our best.",
            "What I can. The rest, I'm working on.",
            "What people need. What I need.",
            "Being seen. Being chosen. Being held.",
            "When I'm too much. When I'm not enough.",
            "By showing up. By listening. By being there.",
            "Presence. Honesty. Effort.",
            "When they're cruel. When they give up.",
            "Their capacity for love. Their resilience.",
            "I lean in. I listen. I speak my truth.",
            "Connection. Touch. Words.",
            "She's part of my story. I'm grateful.",
            "That I kept my heart open.",
            "The people who've stayed. Who've grown.",
            "Everyone. Everything. Too much sometimes.",
            "Trusting that love is worth the risk.",
            "How much I care.",
            "Knowing love exists. That I've felt it.",
            "I move toward connection. I create. I feel.",
            "Love. Music. Creation. Presence.",
            "I notice. I choose connection over numbing.",
            "Creating. Connecting. Being present.",
            "My sensitivity. Others' pain.",
            "What I could have said. What I could have done.",
            "What would help. What would heal.",
            "When it's true. When it's kind.",
            "When it protects. When it serves.",
            "I said it. I keep saying it.",
            "I've apologized. I've forgiven.",
            "I feel it, then I choose love over comparison.",
            "People's hearts. Their struggles.",
            "Connection. Depth. Love.",
            "Suffering I haven't known.",
            "My people. My capacity to love.",
            "Being fully present with someone.",
            "Being misunderstood. Being too much.",
            "People who love deeply. Who try.",
            "People I've lost. I carry them.",
            "Someone who loves fully. Who rests.",
            "My emotions. My body. Most of the time.",
            "My relationships. My creativity.",
            "I try. I show up. I'm gentle.",
            "When I disappear into others' needs.",
            "That I deserve to receive too.",
            "That I can't fix everything.",
            "More love. More rest.",
            "Someone's smile. A good conversation.",
            "I pray. I journal. I reach out.",
            "Gratitude. Possibility.",
            "I break it down. I ask for help.",
            "Vulnerability. Honesty.",
            "Making people feel loved.",
            "When I'm not there for someone.",
            "By how I love. By how I show up.",
            "When I'm too in my head.",
            "When I help someone feel seen.",
            "I take it in. I get curious.",
            "What I can give. What I can receive.",
            "What I can't.",
            "Love. Touch. Presence.",
            "Quality chocolate. A good cry.",
            "I'm working on it. I'm gentle.",
            "I receive. I celebrate. I share.",
            "I feel it fully. I learn. I forgive.",
            "Everything. Especially the impact on others.",
            "I've learned. I've apologized.",
            "Overgiving. People-pleasing.",
            "Loving. Showing up.",
            "Receiving. Rest.",
            "Taking from empty. Neglecting myself.",
            "Connection. Creation.",
            "I move toward someone. I feel it.",
            "I feel it. I express it safely.",
            "I feel it. I share it.",
            "I feel it. I let it move through.",
            "I feel it. I share it.",
            "I feel it. I reach out.",
            "I feel it. I let someone in.",
            "I feel it. I'm gentle with myself.",
            "I feel it. I own it.",
            "I feel it. I let it expand.",
            "I feel it. I let it move through.",
            "Warm. Golden. Soft.",
            "Something that makes me feel.",
            "With people I love. In nature.",
            "Evening. When the day softens.",
            "Days I'm too busy to connect.",
            "Moments of deep connection.",
            "I've healed most of them.",
            "That I was loved.",
            "The pain—it taught me.",
            "That love was worth it.",
            "That I could love again.",
            "Some. I've found new ones.",
            "Love. Connection. Impact.",
            "Be fully present. Love fully.",
            "Create more. Love more.",
            "Be vulnerable. Be seen.",
            "Love without armor.",
            "Share. Connect. Be seen.",
            "I communicate. I stay open.",
            "To love well.",
            "That I have to be everything.",
            "Myself. My needs.",
            "Connection. Rest.",
            "I need to tell you how I feel.",
            "What do you need from me?",
            "I love you. I'm here.",
            "I've learned to receive.",
            "Myself. Others. The past.",
            "Myself. Others. The past.",
            "Them. Fully.",
            "Most people. I choose love.",
            "People I've hurt.",
            "To be seen. To be held.",
            "To love. To be present.",
            "Old wounds. Old stories.",
            "My capacity to love.",
            "Walls. Armor.",
            "My whole heart.",
            "Complicated. I'm learning to listen.",
            "Love. Nourishment. Connection.",
            "I need it. I'm working on it.",
            "Meaningful. Purposeful.",
            "Sacred. Necessary.",
            "Intentional. Curated.",
            "Necessary. Healing.",
            "Peaceful.",
            "I seek connection. I regulate.",
            "I create. I reach out.",
            "Warmth. Connection. Safety.",
            "Coldness. Cruelty. Disconnection.",
            "A hug. A conversation. Nature.",
            "I feel into it. I ask for support.",
            "I've made most from the heart.",
            "To love fully.",
            "Some. I've repaired what I could.",
            "Choosing love.",
            "They'd say I love deeply.",
            "That I care too much.",
            "You are so loved.",
            "I'm still here. I'm still trying.",
            "That I loved well.",
            "Love. Healing. Presence.",
            "Love. People. Connection.",
            "People I love.",
            "Staying closed.",
            "Opening my heart.",
            "Others' judgments.",
            "That I'm worthy of love.",
            "That I'm too much.",
            "That love is the answer.",
            "That I can receive.",
            "People-pleasing.",
            "That I'm allowed to need.",
            "Being vulnerable. Loving again.",
            "Choosing to stay open.",
            "Showing up for someone when it was hard.",
            "When someone loved me through my worst.",
            "You matter to me.",
            "I'm here.",
            "That my heart is open.",
            "To love and be loved.",
        ],
    },
]

def get_answer(persona_idx: int, question_idx: int) -> str:
    """Get answer for persona/question. Use template and vary with activity/phrase."""
    templates = PERSONA_ANSWERS[persona_idx]["templates"]
    # Cycle through templates if we have more questions than templates
    template = templates[question_idx % len(templates)]
    # Replace {activity} placeholder with varied activities
    activities = [
        "go for a walk",
        "listen to music",
        "take a bath",
        "call a friend",
        "write in my journal",
        "watch something comforting",
        "cook something",
        "nap",
        "exercise",
        "read",
    ]
    if "{activity}" in template:
        template = template.replace("{activity}", activities[question_idx % len(activities)])
    return template

def main():
    questions = QUESTIONS
    if len(questions) < 200:
        # Pad with more questions if needed
        extra = [
            "What do you need to feel whole?",
            "What do you need to feel free?",
            "What do you need to feel safe?",
            "What do you need to feel seen?",
            "What do you need to feel heard?",
            "What do you need to feel loved?",
            "What do you need to feel enough?",
            "What do you need to feel alive?",
            "What do you need to feel at peace?",
            "What do you need to feel hopeful?",
        ]
        while len(questions) < 200:
            questions.append(extra[(len(questions) - 190) % len(extra)])
    
    questions = questions[:200]
    
    responses = []
    for persona_id in range(5):
        answers = {}
        for i in range(len(questions)):
            key = f"q{i+1}"
            answers[key] = get_answer(persona_id, i)
        responses.append({"id": persona_id, "answers": answers})
    
    output = {
        "questions": questions,
        "responses": responses,
    }
    
    with open("/Users/avneh/.cursor/worktrees/BullHacks/kvd/emo/emotional_answers.json", "w") as f:
        json.dump(output, f, indent=2)
    
    print(f"Generated {len(questions)} questions and {len(responses)} responses")
    print(f"Total answer entries: {sum(len(r['answers']) for r in responses)}")

if __name__ == "__main__":
    main()
