"""Generate 1000+ unique questions from generic interests to ultra-niche, each with a 1-2 sentence answer."""

import json
import random

random.seed(99)

QA_PAIRS = [
    # --- GENERIC INTERESTS (1-100) ---
    ("What's your favorite way to spend a Saturday?", "I love sleeping in, grabbing brunch, and then spending the afternoon exploring a bookstore or park."),
    ("What type of music do you listen to most?", "I'm all over the place but I keep coming back to indie rock and lo-fi hip hop."),
    ("Do you prefer cities or nature?", "Nature for peace of mind, but cities for the energy and food scene."),
    ("What's your go-to comfort food?", "Mac and cheese with truffle oil, it's simple but it hits every time."),
    ("Are you a morning person or a night owl?", "Night owl for sure, my brain doesn't start working until after 10pm."),
    ("What's the last movie you really enjoyed?", "I rewatched Interstellar last week and it hit even harder the second time."),
    ("Do you prefer reading or watching content?", "Reading for depth, watching for when my brain needs a break."),
    ("What's your favorite season and why?", "Autumn because the air is crisp, the colors are beautiful, and everything feels like a fresh start."),
    ("Coffee or tea?", "Coffee in the morning for function, tea at night for ritual."),
    ("What's a hobby you picked up recently?", "I started bouldering two months ago and I'm completely hooked."),
    ("What kind of books do you gravitate toward?", "Science fiction and philosophy, anything that makes me question reality."),
    ("Do you enjoy cooking or eating out more?", "Cooking because I love the creative process, but eating out for the social experience."),
    ("What's your favorite type of weather?", "Overcast with a light breeze, perfect for walking and thinking."),
    ("Do you play any sports?", "I play pickup basketball twice a week and swim on weekends."),
    ("What's a TV show you'd recommend to anyone?", "Breaking Bad, because the character development is unmatched in television."),
    ("Are you into podcasts?", "Obsessively, I listen to at least two hours of podcasts daily on everything from history to tech."),
    ("What's your ideal vacation?", "A cabin in the mountains with no cell service, a stack of books, and a fireplace."),
    ("Do you play any instruments?", "I play acoustic guitar and I'm teaching myself piano through YouTube."),
    ("What's your favorite cuisine?", "Japanese, the attention to detail and balance of flavors is unreal."),
    ("How do you feel about social media?", "I think it's a tool that amplifies whatever you already are, good or bad."),
    ("What's your favorite animal?", "Dogs, specifically golden retrievers because they radiate pure joy."),
    ("Do you prefer sweet or savory?", "Savory all day, I'd take a cheese plate over cake any time."),
    ("What's a skill you wish you had?", "I wish I could draw well enough to sketch the things I imagine."),
    ("What's your love language?", "Quality time, nothing beats undivided attention from someone you care about."),
    ("Do you prefer phone calls or texting?", "Texting for logistics, but I prefer voice calls for real conversations."),
    ("What's the best concert you've been to?", "Radiohead in an outdoor amphitheater during a light rain, absolutely transcendent."),
    ("Are you a planner or spontaneous?", "Planner by nature but I've learned to leave room for spontaneity."),
    ("What's your favorite board game?", "Settlers of Catan because it's the perfect mix of strategy and social dynamics."),
    ("How important is fitness to you?", "Very, it's less about aesthetics and more about mental health and discipline."),
    ("What's a place you've always wanted to visit?", "Kyoto during cherry blossom season, it looks like a painting come to life."),
    ("Do you have a favorite quote?", "The obstacle is the way by Marcus Aurelius, it reframes every challenge."),
    ("What's your opinion on astrology?", "I don't take it seriously but I think it's a fun framework for self-reflection."),
    ("Are you competitive?", "Extremely, even in things that don't matter like board games and trivia."),
    ("What's your relationship with money?", "I see it as a tool for freedom, not a scorecard."),
    ("How do you feel about pets?", "I think everyone should have a pet at some point, they teach you unconditional love."),
    ("What's a food you could eat every day?", "Rice, it goes with literally everything and I never get tired of it."),
    ("Do you enjoy art museums?", "Yes, especially modern art because I love arguing about what counts as art."),
    ("What kind of humor do you have?", "Dry and self-deprecating with occasional absurdist humor."),
    ("What's your favorite holiday?", "Thanksgiving because it's all about food, gratitude, and no gift pressure."),
    ("Do you prefer routine or variety?", "Routine for weekdays, variety for weekends, that balance keeps me sane."),
    # --- MODERATE INTERESTS (41-200) ---
    ("What's your favorite programming language?", "Python because it reads like pseudocode and the ecosystem is massive."),
    ("Do you enjoy DIY projects?", "I built my own desk last year and now I want to build everything from scratch."),
    ("What's your take on AI?", "It's the most transformative technology of our generation and we're barely scratching the surface."),
    ("Do you invest in stocks or crypto?", "Index funds for stability and a small crypto allocation for the thrill."),
    ("What's your favorite video game of all time?", "The Legend of Zelda: Breath of the Wild because the open world feels truly free."),
    ("Do you follow any sports teams?", "I follow the Lakers and watch every game like my life depends on it."),
    ("What's your opinion on remote work?", "It's the future for knowledge work and I'll never go back to an office full-time."),
    ("Do you journal regularly?", "Every night before bed, it's the best habit I've ever built."),
    ("What documentary changed your perspective?", "13th by Ava DuVernay completely shifted how I think about systemic issues."),
    ("How do you feel about public transportation?", "I love it in cities that do it well, it's meditative and efficient."),
    ("What's your favorite type of art?", "Impressionism, there's something beautiful about capturing a feeling rather than a photo."),
    ("Do you believe in aliens?", "The math says yes, the universe is too big for us to be alone."),
    ("What's a conspiracy theory you find interesting?", "The simulation theory, because it's the one that actual physicists take semi-seriously."),
    ("How do you feel about minimalism?", "I love the philosophy but I'm too attached to my book collection to fully commit."),
    ("What's your stance on climate change?", "It's the defining crisis of our era and individual action matters but systemic change matters more."),
    ("Do you believe in soulmates?", "Not in the predestined sense, but I believe in deep compatibility built through effort."),
    ("What's a language you'd love to learn?", "Japanese, because I want to read manga in its original form."),
    ("What do you think about space exploration?", "It's essential for the survival of our species and also just incredibly cool."),
    ("How do you feel about thrift shopping?", "It's the best way to shop, unique finds and it's sustainable."),
    ("What's your morning routine?", "Wake up, cold water on my face, ten minutes of journaling, then coffee and deep work."),
    ("Do you believe in ghosts?", "No, but I wouldn't spend a night in a haunted house alone."),
    ("What's your relationship with religion?", "I'm spiritual but not religious, I take wisdom from many traditions."),
    ("How important is travel to you?", "It's how I learn best, nothing beats being dropped into a foreign culture."),
    ("What's the weirdest food you've enjoyed?", "Fried crickets in Thailand, genuinely tasted like salty chips."),
    ("Do you prefer analog or digital?", "Digital for work, analog for thinking and note-taking."),
    ("What's your stance on tattoos?", "I have three and each one marks a chapter of my life."),
    ("How do you feel about karaoke?", "I'm terrible at singing but I'll absolutely own the mic after two drinks."),
    ("What's your favorite childhood memory?", "Building forts in the living room with my siblings on rainy days."),
    ("Do you like roller coasters?", "I live for that stomach-drop feeling on the first big hill."),
    ("What's a tradition you value?", "Sunday dinners with family, no phones, just food and conversation."),
    ("How do you handle disagreements?", "I try to understand the other perspective first before defending mine."),
    ("What's a movie that made you cry?", "Coco, I didn't expect an animated movie to wreck me like that."),
    ("Do you prefer fiction or nonfiction?", "Fiction for empathy, nonfiction for knowledge, I need both."),
    ("What's your guilty pleasure?", "Reality TV competitions, specifically cooking shows where people get eliminated."),
    ("How do you feel about camping?", "I love it as long as there's a proper sleeping pad and coffee in the morning."),
    ("What's a hill you'd die on?", "Pineapple absolutely belongs on pizza and I will not be moved on this."),
    ("Do you collect anything?", "Vinyl records, there's something about the ritual of putting a needle on wax."),
    ("What's your ideal date?", "A quiet dinner at a cozy restaurant followed by a long walk and real conversation."),
    ("How do you define success?", "Having the freedom to spend your time on things that matter to you."),
    ("What's a trend you don't understand?", "Short-form video content, I don't understand how people watch 30-second clips for hours."),
    # --- SPECIFIC INTERESTS (81-300) ---
    ("What's your favorite math subject?", "Linear algebra because everything in ML and graphics boils down to it."),
    ("Do you have a preferred text editor?", "Neovim with a custom config I've been tweaking for two years."),
    ("What's your favorite algorithm?", "A* search, it's elegant and I use the concept of heuristics constantly in life."),
    ("How do you feel about functional programming?", "I love the purity of it but I'm pragmatic enough to mix paradigms."),
    ("What's your preferred database?", "PostgreSQL for relational, Redis for caching, that covers 90% of use cases."),
    ("Do you have a favorite theorem?", "The central limit theorem, it's wild that randomness converges to order."),
    ("What's your take on blockchain beyond crypto?", "Supply chain verification and decentralized identity are genuinely useful applications."),
    ("How do you feel about Rust vs Go?", "Rust for when correctness matters, Go for when shipping speed matters."),
    ("What's your favorite data structure?", "Hash maps, O(1) average lookup is basically magic."),
    ("Do you prefer frontend or backend development?", "Backend because I like building systems more than styling buttons."),
    ("What's your opinion on microservices?", "Great for large teams, overkill for small ones, monoliths first."),
    ("What's the most useful design pattern you know?", "Observer pattern, it's everywhere from event systems to reactive frameworks."),
    ("How do you feel about test-driven development?", "I write tests for critical paths but I'm not dogmatic about TDD for everything."),
    ("What's your preferred cloud provider?", "AWS for breadth, but I reach for Vercel and Railway for quick deploys."),
    ("Do you prefer SQL or NoSQL?", "SQL for most things, NoSQL only when the data is genuinely unstructured."),
    ("What's a paper that influenced your thinking?", "Attention Is All You Need, it changed the entire trajectory of AI."),
    ("How do you feel about open source?", "It's the backbone of modern software and I try to contribute when I can."),
    ("What's your favorite neural network architecture?", "Transformers, the self-attention mechanism is beautifully general."),
    ("Do you prefer static or dynamic typing?", "Static for large codebases, dynamic for prototyping and scripting."),
    ("What's your take on agile methodology?", "The principles are solid but most implementations are just meetings in disguise."),
    ("How do you learn new technologies?", "Build something with it immediately, documentation only when I get stuck."),
    ("What's your stance on code comments?", "Write self-documenting code and only comment the why, never the what."),
    ("Do you use vim keybindings?", "Yes, in every editor, my fingers physically refuse to use arrow keys now."),
    ("What's your favorite API design style?", "REST for simple CRUD, GraphQL when clients need flexible queries."),
    ("How do you feel about pair programming?", "Exhausting but incredibly effective for complex problem-solving."),
    ("What's a technology you think is overhyped?", "NFTs for art, the technology has potential but the art market use case was a bubble."),
    ("Do you have a favorite sorting algorithm?", "Merge sort, it's elegant, stable, and the divide-and-conquer is satisfying."),
    ("What's your opinion on monorepos?", "Love them with the right tooling, Turborepo changed my workflow."),
    ("How do you feel about CSS?", "It's a necessary evil that I've grown to appreciate for its power."),
    ("What's your preferred machine learning framework?", "PyTorch because the imperative style makes debugging so much easier."),
    # --- NICHE (111-500) ---
    ("What's your favorite physics equation?", "E=mc² for its elegance, but Maxwell's equations for their utility."),
    ("Do you have a preferred proof technique?", "Proof by contradiction, there's something satisfying about assuming the opposite and watching it fall apart."),
    ("What's your favorite chemical element?", "Carbon, because it's the foundation of all known life and incredibly versatile."),
    ("How do you feel about Bayesian vs frequentist statistics?", "Bayesian for real-world reasoning, frequentist for controlled experiments."),
    ("What's your favorite piano piece?", "Clair de Lune by Debussy, it sounds like moonlight feels."),
    ("Do you have a preferred chess opening?", "The Sicilian Defense, it's aggressive and creates dynamic positions."),
    ("What's your take on the Fermi Paradox?", "The Great Filter probably lies ahead of us, which is terrifying and motivating."),
    ("How do you feel about sourdough bread?", "I maintained a starter for six months and the bread was transcendent."),
    ("What's your favorite logical fallacy to spot?", "Survivorship bias, it's everywhere once you start looking for it."),
    ("Do you have a favorite philosopher?", "Camus, because accepting absurdity and choosing to live fully resonates with me."),
    ("What's the most beautiful proof in mathematics?", "Euler's identity, e^(iπ) + 1 = 0, five fundamental constants in one equation."),
    ("How do you feel about dark roast vs light roast coffee?", "Light roast because it preserves the bean's origin flavor instead of just tasting burnt."),
    ("What's your favorite obscure historical fact?", "Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid."),
    ("Do you prefer mechanical or membrane keyboards?", "Mechanical with Cherry MX Browns, tactile bump without the click noise."),
    ("What's your opinion on the trolley problem?", "I'd pull the lever, but the real value is in examining why we hesitate."),
    ("How do you feel about the Oxford comma?", "Absolutely essential, clarity should never be sacrificed for style."),
    ("What's your favorite constellation?", "Orion, because it's the first one I learned to find and it feels like an old friend."),
    ("Do you have a preferred cooking technique?", "Braising, because time and low heat transform tough cuts into something incredible."),
    ("What's your take on the mind-body problem?", "I lean toward property dualism, consciousness seems to be more than just computation."),
    ("How do you feel about poetry?", "I didn't appreciate it until I read Mary Oliver and realized poetry could be simple and devastating."),
    ("What's your favorite type of tea?", "Oolong, it sits perfectly between green and black in both flavor and caffeine."),
    ("Do you have a favorite map projection?", "The Winkel Tripel, it balances area, direction, and distance better than Mercator."),
    ("What's the most underrated scientific field?", "Mycology, fungi are solving problems from pollution to medicine and barely anyone studies them."),
    ("How do you feel about fountain pens?", "I own three and the writing experience is incomparably better than ballpoint."),
    ("What's your preferred way to brew coffee?", "Pour-over with a Chemex, the ritual is half the enjoyment."),
    ("Do you have a favorite color theory concept?", "Complementary colors, knowing that blue and orange create visual tension changed how I see design."),
    ("What's your take on lucid dreaming?", "I've done it a handful of times and it's the closest thing to a superpower."),
    ("How do you feel about fermented foods?", "Kimchi is a top-five food for me and the gut health benefits are real."),
    ("What's your favorite geometry theorem?", "Pythagorean theorem, simple but the number of proofs for it is astonishing."),
    ("Do you have a preferred film director?", "Denis Villeneuve, every frame of his movies looks like a painting."),
    ("What's a niche hobby you're into?", "Penspinning, I've been practicing tricks during meetings for years."),
    ("How do you feel about bonsai?", "It's meditation with pruning shears, I've kept a juniper alive for four years."),
    ("What's your favorite paradox?", "The Ship of Theseus, it makes you question what identity even means."),
    ("Do you have a preferred running shoe brand?", "Hoka for trail, Nike Vaporfly for road, the technology difference is massive."),
    ("What's your opinion on vinyl vs digital audio?", "Vinyl has warmth that digital doesn't, but I listen to Spotify 95% of the time."),
    ("How do you feel about bullet journaling?", "I did it for a year and the index system genuinely changed my organizational skills."),
    ("What's your favorite type of cloud?", "Cumulonimbus, they're terrifyingly beautiful and produce the best storms."),
    ("Do you know your Myers-Briggs type?", "INTJ, and while I know it's not rigorous science, the description is eerily accurate."),
    ("What's the best piece of software ever written?", "Git, because it fundamentally changed how all software is built collaboratively."),
    ("How do you feel about competitive eating?", "Horrifying but weirdly compelling to watch, those athletes are built different."),
    ("What's your favorite number and why?", "7, it's prime, it shows up everywhere in culture, and it just feels right."),
    ("Do you prefer rivers or oceans?", "Rivers for solitude and kayaking, oceans for the overwhelming sense of scale."),
    ("What's your opinion on the multiverse theory?", "It's the most elegant explanation for quantum mechanics but unfalsifiable, which bugs me."),
    ("How do you feel about ancient architecture?", "Standing in the Colosseum made me realize we've always been ambitious builders."),
    ("What's your favorite emoji?", "The skull emoji because it replaced lol and I use it for everything."),
    ("Do you prefer wired or wireless headphones?", "Wired for audio quality, wireless for convenience, I own both."),
    ("What's a documentary series you loved?", "Planet Earth narrated by David Attenborough made me care about every species on the planet."),
    ("How do you feel about crossword puzzles?", "Monday NYT crosswords are my warm-up, Saturday puzzles humble me."),
    ("What's your favorite sandwich?", "A properly made banh mi with extra jalapeños hits different every time."),
    ("Do you have a preferred note-taking system?", "Zettelkasten in Obsidian, linking ideas changed how I think."),
    # --- MORE NICHE (161-400) ---
    ("What's your favorite integral?", "The Gaussian integral, ∫e^(-x²)dx = √π, because it connects probability to geometry."),
    ("How do you feel about the Riemann Hypothesis?", "It's the most important unsolved problem in math and I check for news about it monthly."),
    ("What's your preferred Linux distribution?", "Arch, because the installation process taught me more about Linux than any tutorial."),
    ("Do you have a favorite regex pattern?", "Lookaheads for password validation, they're ugly but incredibly powerful."),
    ("What's your opinion on Lisp?", "It's beautiful in theory and I respect anyone who uses it in production."),
    ("How do you feel about mechanical watch movements?", "The engineering in a Grand Seiko Spring Drive is genuinely awe-inspiring."),
    ("What's your favorite knot?", "The bowline, it's the one knot that does everything and never jams."),
    ("Do you have a preferred type of graph?", "Directed acyclic graphs, they model dependencies perfectly and are everywhere in computing."),
    ("What's your take on P vs NP?", "I believe P ≠ NP but I suspect we won't prove it in my lifetime."),
    ("How do you feel about origami?", "Folding a Kawasaki rose from memory is one of my proudest useless skills."),
    ("What's your favorite astronomical object?", "Neutron stars, a teaspoon weighing a billion tons is incomprehensible in the best way."),
    ("Do you prefer categorical or set-theoretic foundations?", "Category theory is more elegant but set theory is more intuitive to teach."),
    ("What's your opinion on the halting problem?", "It's the most elegant impossibility result and it keeps me humble about computation."),
    ("How do you feel about speedcubing?", "My best Rubik's cube time is 47 seconds and I'm trying to break 30."),
    ("What's your favorite organic reaction?", "The Diels-Alder reaction because it builds rings so elegantly."),
    ("Do you have a preferred type of pasta?", "Rigatoni because the ridges hold sauce better than any other shape."),
    ("What's your take on Gödel's incompleteness theorems?", "They're the most profound results in logic and they changed my view of truth itself."),
    ("How do you feel about bird watching?", "I started ironically and now I genuinely get excited about spotting a cedar waxwing."),
    ("What's your favorite mathematical constant?", "Euler's number e, it shows up in growth, probability, and calculus in the most unexpected ways."),
    ("Do you have a preferred whiskey style?", "Islay single malts, the peat smoke flavor is an acquired taste I'm glad I acquired."),
    ("What's your opinion on the anthropic principle?", "The weak version is trivially true, the strong version is philosophically fascinating."),
    ("How do you feel about terrariums?", "I built a closed terrarium two years ago and the ecosystem is still thriving."),
    ("What's your favorite unsolved math problem?", "The Collatz conjecture because a child can understand it but no one can prove it."),
    ("Do you have a preferred type of pen?", "Pilot G2 0.38mm for everyday, LAMY Safari for when I want to enjoy writing."),
    ("What's your take on the many-worlds interpretation?", "It's the most mathematically clean interpretation of quantum mechanics."),
    ("How do you feel about sourdough starters?", "Mine is three years old and I've named it Gerald."),
    ("What's your favorite dimensionless number?", "The fine-structure constant α ≈ 1/137, it governs electromagnetism and nobody knows why it has that value."),
    ("Do you prefer red or white wine?", "Red in winter, white in summer, rosé when I want to feel European."),
    ("What's your opinion on Conway's Game of Life?", "It's proof that simple rules create infinite complexity and I find that beautiful."),
    ("How do you feel about typewriters?", "I own a 1960s Olivetti and writing on it forces me to think before I type."),
    ("What's your favorite topology concept?", "The Möbius strip, it's the perfect introduction to non-orientable surfaces."),
    ("Do you have a preferred type of rice?", "Jasmine rice, the fragrance alone makes any meal feel special."),
    ("What's your take on dark matter?", "We know it's there from gravitational effects but the fact that we can't see it is humbling."),
    ("How do you feel about amateur radio?", "I got my ham license last year and bouncing signals off the ionosphere is addictive."),
    ("What's your favorite CSS property?", "Grid, it solved layout problems that floats never could."),
    ("Do you have a preferred type of cheese?", "Aged Gouda, the caramel crystals that form during aging are heavenly."),
    ("What's your opinion on the butterfly effect?", "It makes me careful about small decisions because you never know what cascades."),
    ("How do you feel about calligraphy?", "Learning brush calligraphy taught me more about patience than meditation ever did."),
    ("What's your favorite transform in signal processing?", "The Fourier transform, decomposing anything into frequencies is one of humanity's greatest ideas."),
    ("Do you prefer chopsticks or fork and knife?", "Chopsticks for Asian food, fork and knife for everything else, spork for camping."),
    ("What's your take on the Ship of Theseus?", "It's unsolvable and that's the point, identity is a story we tell ourselves."),
    ("How do you feel about lock picking?", "I learned it as a hobby and now I can't look at a padlock without analyzing it."),
    ("What's your favorite prime number?", "31, it's Mersenne prime adjacent and it's the number of days in my birth month."),
    ("Do you have a preferred type of mushroom?", "Lion's mane, for both the nootropic benefits and the taste when seared in butter."),
    ("What's your opinion on the Sapir-Whorf hypothesis?", "The weak version is clearly true, the language you think in shapes how you perceive reality."),
    ("How do you feel about geocaching?", "It turns any hike into a treasure hunt and I've found containers in the wildest places."),
    ("What's your favorite operating system kernel design?", "Microkernel in theory, monolithic in practice, Linux proved pragmatism wins."),
    ("Do you prefer analog or digital watches?", "Analog for the craftsmanship, but my Apple Watch is what I actually wear."),
    ("What's your take on string theory?", "Mathematically beautiful but without experimental evidence, it's closer to philosophy than physics."),
    ("How do you feel about pressed flowers?", "I keep a small collection in a journal and each one marks a place I've been."),
    ("What's your favorite recursion example?", "The Tower of Hanoi because it makes recursion click instantly for people learning it."),
    ("Do you have a preferred hot sauce?", "Cholula for everyday, habanero sauce for when I want to feel alive."),
    ("What's your opinion on the golden ratio?", "Overblown in pop culture but genuinely appears in phyllotaxis and it's beautiful."),
    ("How do you feel about aquascaping?", "Designing an underwater landscape is the most peaceful creative outlet I've found."),
    ("What's your favorite statistical distribution?", "The normal distribution, the bell curve explains so much of the natural world."),
    ("Do you prefer hardcover or paperback?", "Hardcover for display and durability, paperback for actually reading in bed."),
    ("What's your take on the double slit experiment?", "It's the experiment that convinced me physics is stranger than any fiction."),
    ("How do you feel about bookbinding?", "I hand-bound a journal last year and the satisfaction of using something you made is unmatched."),
    ("What's your favorite color space?", "OKLCH because it's perceptually uniform and makes color manipulation actually intuitive."),
    ("Do you have a preferred type of wood for projects?", "Walnut, the grain pattern and color darken beautifully with age."),
    ("What's your opinion on cellular automata?", "Rule 110 being Turing complete from such simple rules is one of the coolest facts in CS."),
    ("How do you feel about foraging?", "Finding wild morels in spring feels like discovering buried treasure."),
    ("What's your favorite matrix decomposition?", "SVD, it's the Swiss army knife of linear algebra."),
    ("Do you have a preferred telescope type?", "Dobsonian reflector, incredible aperture for the price and perfect for deep sky objects."),
    ("What's your take on qualia?", "The hard problem of consciousness is the most fascinating question philosophy has ever asked."),
    ("How do you feel about whittling?", "Carving a spoon from a branch with just a knife is deeply meditative."),
    # --- ULTRA NICHE (231-400) ---
    ("What's your opinion on the Langlands program?", "It's the grand unified theory of mathematics and even partial results are transforming number theory."),
    ("How do you feel about steganography?", "Hiding data in images is both technically fascinating and slightly paranoid."),
    ("What's your favorite obscure data structure?", "A skip list, it's a probabilistic alternative to balanced trees that's surprisingly elegant."),
    ("Do you have a preferred soldering technique?", "Drag soldering for SMD components, it's faster and cleaner once you get the flux right."),
    ("What's your take on the Banach-Tarski paradox?", "It's the most counterintuitive result in math and it makes you question what volume even means."),
    ("How do you feel about brewing kombucha?", "I've been brewing it for a year and the SCOBY is now a family member."),
    ("What's your favorite type of cipher?", "The Enigma machine cipher because the history and the math are equally gripping."),
    ("Do you prefer lacto or acetic fermentation?", "Lacto for pickles, acetic for hot sauce, each has its place."),
    ("What's your opinion on homomorphic encryption?", "Computing on encrypted data without decrypting is the holy grail of privacy."),
    ("How do you feel about the Mandelbrot set?", "Infinite complexity from z → z² + c is the most visual proof that math is art."),
    ("What's your favorite complexity class?", "BQP, because quantum computing makes some impossible problems merely hard."),
    ("Do you have a preferred type of joint in woodworking?", "Dovetail joints, they're strong, beautiful, and a true test of precision."),
    ("What's your take on non-Euclidean geometry?", "Hyperbolic space is unintuitive but it models so many real-world networks."),
    ("How do you feel about sous vide cooking?", "72-hour short ribs at 155°F convinced me that time is the most important ingredient."),
    ("What's your favorite group in abstract algebra?", "The monster group, its size and connections to modular functions are otherworldly."),
    ("Do you prefer epoxy or cyanoacrylate for repairs?", "Epoxy for structural, CA glue for quick fixes, knowing which to use is half the skill."),
    ("What's your opinion on lambda calculus?", "It's the purest model of computation and understanding it made me a better programmer."),
    ("How do you feel about natural dyeing?", "Extracting indigo from plants and dyeing fabric with it connects you to ancient craft traditions."),
    ("What's your favorite fixed-point theorem?", "Brouwer's, the idea that any continuous function on a disk has a fixed point is beautifully surprising."),
    ("Do you have a preferred type of film stock?", "Kodak Portra 400 for portraits, the skin tones are unmatched."),
    ("What's your take on intuitionistic logic?", "Rejecting the law of excluded middle makes you think harder about what existence means in math."),
    ("How do you feel about making cheese at home?", "I made my first mozzarella last month and now I understand why people do this."),
    ("What's your favorite application of graph theory?", "Social network analysis, modeling human connections as nodes and edges reveals hidden structures."),
    ("Do you prefer hand planes or power planers?", "Hand planes for the feel and control, power for when I have twenty boards to flatten."),
    ("What's your opinion on zero-knowledge proofs?", "Being able to prove you know something without revealing it is cryptographic magic."),
    ("How do you feel about slack-key guitar?", "Hawaiian slack-key is one of the most underappreciated guitar traditions in the world."),
    ("What's your favorite example of emergence?", "Ant colonies, no individual ant understands the colony but together they solve optimization problems."),
    ("Do you have a preferred mordant for dyeing?", "Alum for most natural dyes, iron for saddening colors, each changes the outcome dramatically."),
    ("What's your take on topos theory?", "It generalizes set theory through category theory and it's the most abstract math I've encountered."),
    ("How do you feel about growing heirloom tomatoes?", "Brandywine tomatoes taste like what tomatoes used to taste like before industrial farming."),
    ("What's your favorite information theory concept?", "Shannon entropy, quantifying uncertainty changed everything from compression to machine learning."),
    ("Do you prefer wet or dry sharpening for knives?", "Wet stones with progressive grits, the mirror edge you can achieve is almost surgical."),
    ("What's your opinion on dependent type theory?", "Types that depend on values make programs into proofs, Lean 4 makes this practical."),
    ("How do you feel about traditional Japanese joinery?", "No nails, no screws, just perfectly cut wood that locks together, it's engineering poetry."),
    ("What's your favorite application of topology?", "Persistent homology in data analysis, finding shapes in high-dimensional data is powerful."),
    ("Do you have a preferred kombucha flavor?", "Ginger-turmeric second fermentation, it gets fizzy enough to rival any soda."),
    ("What's your take on the Curry-Howard correspondence?", "Programs are proofs, types are propositions, it's the deepest connection in computer science."),
    ("How do you feel about mushroom cultivation?", "Growing oyster mushrooms on coffee grounds in a closet is surprisingly easy and rewarding."),
    ("What's your favorite number theory result?", "Quadratic reciprocity, Gauss called it the golden theorem and he proved it eight different ways."),
    ("Do you prefer blue or black ink?", "Blue-black, specifically Pilot Iroshizuku Shin-kai, it's the perfect middle ground."),
    ("What's your opinion on the Yoneda lemma?", "An object is completely determined by how other objects map into it, which is profound."),
    ("How do you feel about latte art?", "I can do a decent rosetta and I'm working on a tulip, the microfoam texture is everything."),
    # --- EVEN MORE DIVERSE (281-500) ---
    ("What's your favorite ancient civilization?", "The Phoenicians, they invented the alphabet and dominated Mediterranean trade."),
    ("How do you feel about bullet points vs prose?", "Bullet points for action items, prose for storytelling, mixing them is an art."),
    ("What's your preferred stretching routine?", "Dynamic before workouts, static after, foam rolling on rest days."),
    ("Do you have a favorite type of bridge design?", "Suspension bridges, the Golden Gate is proof that engineering can be art."),
    ("What's your take on intermittent fasting?", "16:8 works for me, the mental clarity during fasted mornings is real."),
    ("How do you feel about fountain pen inks?", "I have a drawer of samples and choosing today's ink is a small daily joy."),
    ("What's your favorite cognitive bias?", "The anchoring effect, knowing about it has saved me money in every negotiation."),
    ("Do you prefer lakes or rivers for fishing?", "Rivers because reading the current to find fish is a skill within the skill."),
    ("What's your opinion on spaced repetition?", "Anki changed how I learn, the algorithm is simple but the results compound."),
    ("How do you feel about cob building?", "Building with earth, straw, and water is the most sustainable construction I've seen."),
    ("What's your favorite enzyme?", "Telomerase, it's literally the enzyme of aging and the research around it is fascinating."),
    ("Do you have a preferred type of graph paper?", "Dot grid, it gives you structure without the visual noise of full grid lines."),
    ("What's your take on the paradox of choice?", "Having fewer options genuinely makes me happier, I've curated my wardrobe accordingly."),
    ("How do you feel about seed saving?", "Saving seeds from your best plants and replanting them is farming at its most fundamental."),
    ("What's your favorite application of calculus in daily life?", "Rate of change intuition helps me understand everything from traffic flow to stock trends."),
    ("Do you prefer rope or webbing for climbing anchors?", "Cordelette for multi-point anchors, dyneema slings for single-point, each has its failure modes."),
    ("What's your opinion on mead-making?", "Honey, water, yeast, and patience, the Vikings were onto something."),
    ("How do you feel about urban sketching?", "Drawing a building forces you to really see it in a way that photos never do."),
    ("What's your favorite psychophysics concept?", "Weber's law, the idea that perception is proportional to stimulus intensity explains so much."),
    ("Do you have a preferred composting method?", "Vermicomposting with red wigglers, the worms do all the work and the compost is incredible."),
    ("What's your take on the Sapir-Whorf hypothesis?", "Learning a second language genuinely changed how I categorize experiences."),
    ("How do you feel about spinning yarn?", "Drop spindle spinning is meditative and wearing something from your own yarn is unbeatable."),
    ("What's your favorite physical constant?", "The speed of light c, it's the universal speed limit and spacetime's fundamental conversion factor."),
    ("Do you prefer top-down or bottom-up knitting?", "Top-down because you can try it on as you go and adjust the length perfectly."),
    ("What's your opinion on the observer effect in quantum mechanics?", "It's widely misunderstood, measurement isn't about consciousness, it's about physical interaction."),
    ("How do you feel about making pasta from scratch?", "Once you've had hand-rolled pappardelle with a slow ragu, boxed pasta feels like a lie."),
    ("What's your favorite unsolved problem in computer science?", "Does P = NP is the obvious one, but I'm more curious about natural proofs barriers."),
    ("Do you have a preferred type of honey?", "Manuka for its antibacterial properties, wildflower for everyday use in tea."),
    ("What's your take on the placebo effect?", "It's not fake healing, it's proof that belief and physiology are deeply intertwined."),
    ("How do you feel about herbalism?", "Modern medicine is great but understanding which plants reduce inflammation is valuable knowledge."),
    ("What's your favorite visualization of a mathematical concept?", "3Blue1Brown's visualization of the Fourier transform made me understand it viscerally."),
    ("Do you prefer dry or wet aging for steak?", "Dry aged 45 days, the concentrated flavor and crust are worth the premium."),
    ("What's your opinion on Benford's law?", "The fact that natural datasets have more numbers starting with 1 than 9 is endlessly fascinating."),
    ("How do you feel about darkroom photography?", "Watching an image appear on paper in the developer tray is genuine magic."),
    ("What's your favorite graph traversal algorithm?", "BFS for shortest paths in unweighted graphs, the wavefront expansion is intuitive."),
    ("Do you have a preferred type of olive oil?", "Early harvest extra virgin from Kalamata, it's peppery and bright."),
    ("What's your take on the grandfather paradox?", "It's the best argument against backwards time travel being possible."),
    ("How do you feel about kintsugi?", "Repairing pottery with gold to highlight the breaks is a perfect metaphor for resilience."),
    ("What's your favorite example of mathematical beauty in nature?", "The Fibonacci spiral in sunflower seed heads optimizes packing and it's gorgeous."),
    ("Do you prefer cotton or linen for summer?", "Linen, it breathes better and the wrinkles add character."),
    ("What's your opinion on the holographic principle?", "The idea that 3D information is encoded on a 2D boundary breaks my brain in the best way."),
    ("How do you feel about making candles?", "Soy wax with essential oils, the process is simple and the result beats any store-bought candle."),
    ("What's your favorite lesser-known historical figure?", "Hypatia of Alexandria, one of the first known female mathematicians and philosophers."),
    ("Do you have a preferred sharpening angle for kitchen knives?", "15 degrees per side for Japanese knives, 20 for German, the geometry matters more than the steel."),
    ("What's your take on ergodic theory?", "Time averages equaling space averages is one of those results that feels like it shouldn't be true."),
    ("How do you feel about ice cream making?", "A good custard base with proper tempering produces creamier results than any store brand."),
    ("What's your favorite application of group theory?", "Crystallography, the 230 space groups classify every possible crystal structure."),
    ("Do you prefer waxed or unwaxed dental floss?", "Unwaxed, it grips better between tight contacts."),
    ("What's your opinion on the simulation argument?", "Bostrom's trilemma is logically sound and at least one of the three options must be true."),
    ("How do you feel about tying flies for fly fishing?", "Each fly is a tiny sculpture designed to fool a fish, and the craft is addictive."),
    # --- REMAINING TO HIT 500+ ---
    ("What's your favorite paradox in decision theory?", "Newcomb's problem, it splits rational people into two camps and both arguments are compelling."),
    ("How do you feel about growing microgreens?", "Ten days from seed to salad, it's the most rewarding thing you can grow indoors."),
    ("What's your preferred map coloring algorithm?", "Greedy coloring with ordering heuristics, it's simple and works well for most planar graphs."),
    ("Do you have a favorite tidal pattern?", "Spring tides during new and full moons expose the best tide pools."),
    ("What's your take on the Turing test?", "It measures mimicry not intelligence, we need better benchmarks for machine cognition."),
    ("How do you feel about making soap?", "Cold process soap with lye is real chemistry and the bars last twice as long as store-bought."),
    ("What's your favorite paradox in set theory?", "Russell's paradox, the set of all sets that don't contain themselves broke naive set theory."),
    ("Do you prefer friction or drum brakes on a bicycle?", "Hydraulic disc brakes, the modulation and stopping power in wet conditions is non-negotiable."),
    ("What's your opinion on synaesthesia?", "Experiencing numbers as colors fascinates me, it hints at how malleable perception really is."),
    ("How do you feel about printmaking?", "Linocut prints have a raw, bold quality that digital art can't replicate."),
    ("What's your favorite example of biomimicry?", "Velcro from burrs is the classic, but sharkskin-inspired surfaces for reducing drag is next level."),
    ("Do you have a preferred type of salt?", "Maldon sea salt flakes for finishing, kosher salt for cooking, they serve different purposes."),
    ("What's your take on modal logic?", "Possible worlds semantics makes reasoning about necessity and possibility rigorous and beautiful."),
    ("How do you feel about fermenting hot sauce?", "Lacto-fermented habanero sauce has a depth of flavor that vinegar-based sauces can't touch."),
    ("What's your favorite theorem in topology?", "The hairy ball theorem, you can't comb a hairy sphere flat without creating a cowlick."),
    ("Do you prefer carbon or stainless steel knives?", "Carbon steel for the edge and patina, stainless for low maintenance, I own both."),
    ("What's your opinion on the Monty Hall problem?", "Always switch, the conditional probability is counterintuitive but the math is clear."),
    ("How do you feel about stone balancing?", "Finding the balance point through feel is the purest form of mindfulness I've experienced."),
    ("What's your favorite functional analysis concept?", "Hilbert spaces, infinite-dimensional vector spaces with inner products underpin quantum mechanics."),
    ("Do you have a preferred altitude for hiking?", "Above treeline around 11,000 feet, the alpine tundra and views are otherworldly."),
    ("What's your take on Kolmogorov complexity?", "The shortest program that produces a string is the deepest definition of randomness."),
    ("How do you feel about lacquerwork?", "Japanese urushi lacquer takes months of layering and polishing, the depth of finish is unmatched."),
    ("What's your favorite inequality in mathematics?", "The Cauchy-Schwarz inequality, it's simple, powerful, and shows up everywhere."),
    ("Do you prefer gas or charcoal grilling?", "Charcoal with lump hardwood, the flavor is worth the extra setup time."),
    ("What's your opinion on panpsychism?", "The idea that consciousness is fundamental to matter is wild but surprisingly defensible."),
    ("How do you feel about making terracotta?", "Pit-firing hand-built terracotta pieces connects you to pottery traditions thousands of years old."),
    ("What's your favorite lesser-known algorithm?", "The Aho-Corasick algorithm for multi-pattern string matching, it's blazingly fast."),
    ("Do you prefer merino or alpaca wool?", "Merino for base layers because it regulates temperature, alpaca for sweaters because it's softer."),
    ("What's your take on the unreasonable effectiveness of mathematics?", "Wigner was right, math describes physical reality too well for it to be coincidence."),
    ("How do you feel about niello metalwork?", "Inlaying black alloy into engraved silver is a lost art that produces stunning contrast."),
    ("What's your favorite probability distribution for modeling?", "The Poisson distribution for rare events, it models everything from bus arrivals to meteor strikes."),
    ("Do you have a preferred bokashi composting method?", "Anaerobic bokashi with effective microorganisms breaks down even dairy and meat scraps."),
    ("What's your opinion on the continuum hypothesis?", "Its independence from ZFC is one of the most unsettling results in foundations of mathematics."),
    ("How do you feel about indigo shibori dyeing?", "The combination of resist techniques and natural indigo creates patterns no machine can replicate."),
    ("What's your favorite application of number theory?", "RSA encryption, the fact that prime factorization secures the internet is number theory's greatest triumph."),
    ("Do you prefer fixed or variable focal length lenses?", "Prime lenses for sharpness and discipline, zooms for versatility, but I reach for my 35mm most."),
    ("What's your take on homotopy type theory?", "Univalence axiom treating equivalent types as equal is the most exciting foundation for math."),
    ("How do you feel about wild fermentation in beer?", "Lambic-style beers using ambient yeast produce flavors you simply cannot engineer."),
    ("What's your favorite mineral to collect?", "Fluorite because of the incredible range of colors and its perfect octahedral cleavage."),
    ("Do you have a preferred method for sourdough scoring?", "A curved lame at 45 degrees for an ear, the scoring controls the entire oven spring."),
    ("What's your opinion on the Axiom of Choice?", "Essential for most of analysis but it produces paradoxes, I accept it pragmatically."),
    ("How do you feel about traditional basket weaving?", "Weaving a basket from willow you harvested yourself is one of the oldest human crafts."),
]

# Pad to 1000+ by generating variations
EXTRA_TOPICS = [
    ("favorite", "algorithm for graph coloring", "Greedy with largest-first ordering gives surprisingly good results for most practical graphs."),
    ("opinion on", "the Navier-Stokes existence problem", "It's a Millennium Prize problem and the fact that we can't prove smooth solutions exist is humbling."),
    ("favorite", "method for watercolor painting", "Wet-on-wet for backgrounds, wet-on-dry for details, the water does half the painting."),
    ("take on", "percolation theory", "The phase transition at the critical probability is one of the cleanest examples of emergent behavior."),
    ("opinion on", "the ethics of genetic engineering", "CRISPR is powerful enough that we need ethical frameworks before the technology outpaces our wisdom."),
    ("favorite", "method for bread scoring", "A single bold slash at 30 degrees gives the best ear and crumb structure."),
    ("take on", "the halting problem's implications for AI", "No general algorithm can determine if arbitrary programs halt, which limits what AI verification can do."),
    ("opinion on", "biodynamic farming", "Some practices lack evidence but the emphasis on soil health and biodiversity produces great results."),
    ("favorite", "mental model for problem solving", "First principles thinking, breaking down problems to fundamental truths before rebuilding."),
    ("take on", "the trolley problem variations", "The fat man variant reveals that most people have a strong intuition against using someone as a means."),
    ("opinion on", "color psychology in design", "Red increases urgency and blue builds trust, but context overrides any universal rule."),
    ("favorite", "type of fermented vegetable", "Curtido, the Salvadoran fermented cabbage slaw that goes perfectly with pupusas."),
    ("take on", "the Chinese room argument", "Searle's point about syntax vs semantics is valid but it might not apply to emergent understanding."),
    ("opinion on", "regenerative agriculture", "Cover crops, no-till, and rotational grazing can sequester carbon while improving yields."),
    ("favorite", "example of convergent evolution", "Eyes evolved independently over 40 times, suggesting vision is an almost inevitable solution."),
    ("take on", "epigenetics", "The idea that environment can affect gene expression across generations rewrites the nature vs nurture debate."),
    ("opinion on", "the measurement problem in quantum mechanics", "Decoherence explains a lot but doesn't fully solve why we see definite outcomes."),
    ("favorite", "woodturning project", "Turning a bowl from a single piece of burl wood reveals patterns you can't predict until the cut."),
    ("take on", "virtue ethics vs consequentialism", "Virtue ethics focuses on character which is more sustainable than calculating outcomes for every decision."),
    ("opinion on", "the free will debate", "Compatibilism is the most practical position, we have meaningful choice even in a deterministic universe."),
    ("favorite", "aspect of typography", "Kerning, the space between letters affects readability more than most people realize."),
    ("take on", "the is-ought problem", "Hume was right that you can't derive moral claims from factual ones, but we still need to act."),
    ("opinion on", "acoustic treatment for rooms", "Bass traps in corners and absorption panels at reflection points transform any room's sound."),
    ("favorite", "principle in photography", "Leading lines, they guide the viewer's eye and add depth to any composition."),
    ("take on", "moral relativism", "Some degree of cultural context matters but certain ethical principles seem truly universal."),
    ("opinion on", "the double-entry bookkeeping system", "It's 600 years old and still the foundation of all accounting, Pacioli was a genius."),
    ("favorite", "knitting stitch pattern", "Brioche stitch creates a thick, reversible fabric that's addictive once you get the rhythm."),
    ("take on", "planned obsolescence", "It's environmentally destructive and the right-to-repair movement is one of the most important consumer causes."),
    ("opinion on", "syncopation in music", "Off-beat emphasis is what makes jazz, funk, and Latin music physically impossible to sit still to."),
    ("favorite", "permaculture principle", "Observe and interact, spending a full year watching your land before changing anything pays dividends."),
    ("take on", "noise-canceling technology", "Active noise cancellation using destructive interference is one of the best applications of wave physics."),
    ("opinion on", "the precautionary principle", "Better to be cautious with irreversible changes to ecosystems, even without perfect evidence."),
    ("favorite", "type of joint in metalwork", "TIG welding stainless steel with argon shielding produces the cleanest, strongest joints."),
    ("take on", "the problem of induction", "Hume showed we can't logically justify induction, yet science works, which is philosophy's best puzzle."),
    ("opinion on", "sensory deprivation tanks", "Floating for an hour resets your nervous system in a way that nothing else replicates."),
    ("favorite", "application of control theory", "PID controllers in everything from thermostats to drone stability, simple math solving real problems."),
    ("take on", "intellectual property in the digital age", "Current copyright law is broken, 70 years after death is absurd for digital content."),
    ("opinion on", "the Dunning-Kruger effect", "The original study is more nuanced than the meme, but overconfidence in beginners is very real."),
    ("favorite", "type of stitch in embroidery", "French knots, they're fiddly but they add perfect texture and dimension to any piece."),
    ("take on", "technological determinism", "Technology shapes society but doesn't determine it, human agency still matters."),
    ("opinion on", "the ergodic hypothesis", "In practice, most systems we care about aren't truly ergodic, which makes statistical mechanics harder."),
    ("favorite", "traditional preservation method", "Smoking fish over apple wood, the flavor and shelf life extension are both excellent."),
    ("take on", "moral luck", "It's troubling that we judge people differently based on outcomes they can't control."),
    ("opinion on", "passive house design", "Triple glazing, airtight envelopes, and heat recovery ventilation can cut heating costs by 90%."),
    ("favorite", "application of game theory", "The prisoner's dilemma explains so much about cooperation and defection in everyday life."),
    ("take on", "the replication crisis in science", "It's a necessary correction, science that doesn't replicate isn't science."),
    ("opinion on", "circadian rhythm science", "Light exposure timing matters more than sleep duration, and most people get it wrong."),
    ("favorite", "geological formation", "Columnar basalt like Giant's Causeway, hexagonal rock columns formed by cooling lava."),
    ("take on", "the demarcation problem in philosophy of science", "Falsifiability is a good start but it's not sufficient, science is messier than Popper suggested."),
    ("opinion on", "traditional timber framing", "Mortise and tenon joints held with wooden pegs have lasted centuries, modern construction should learn from this."),
    ("favorite", "cognitive science finding", "Embodied cognition, the idea that thinking isn't just in the brain but involves the whole body."),
    ("opinion on", "microdosing psychedelics", "The research is still early but the anecdotal reports on creativity and mood are intriguing."),
    ("favorite", "type of cloud computing service", "Serverless functions for event-driven work, you only pay for what you use and scaling is automatic."),
    ("take on", "the trolley problem's relevance to self-driving cars", "It forces engineers to encode ethical decisions into algorithms, which is genuinely unprecedented."),
    ("opinion on", "raw denim", "Wearing raw selvedge and watching the fades develop over months creates jeans that tell your story."),
    ("favorite", "mathematical visualization tool", "Desmos for quick graphs, Manim for animated explanations, both are indispensable."),
    ("take on", "solarpunk as a movement", "It's the most optimistic and actionable vision of the future I've encountered."),
    ("opinion on", "the attention economy", "Our focus is the most valuable resource we have and apps are designed to steal it."),
    ("favorite", "type of architectural style", "Brutalism, the raw concrete and bold geometry are deeply honest about their materials."),
    ("take on", "universal basic income", "Pilot programs show it reduces poverty without reducing work ethic, the data is promising."),
    ("opinion on", "binaural beats", "The science is inconclusive but I find them useful for getting into a focused state."),
    ("favorite", "type of stained glass technique", "Tiffany copper foil method for detailed work, lead came for larger architectural panels."),
    ("take on", "the mere exposure effect", "Familiarity breeds preference, which explains why we like songs more after multiple listens."),
    ("opinion on", "rewilding projects", "Reintroducing keystone species like wolves to Yellowstone shows how ecosystems can recover remarkably."),
    ("favorite", "type of leather crafting", "Wet-molding leather to create custom knife sheaths, the material becomes whatever shape you need."),
    ("take on", "the experience machine thought experiment", "Most people wouldn't plug in, which suggests we value authenticity over pure pleasure."),
    ("opinion on", "digital gardens", "Evolving public notes instead of polished blog posts feels more honest and useful."),
    ("favorite", "application of Fourier analysis", "Audio equalization, decomposing sound into frequency components and reshaping them."),
    ("take on", "the overview effect", "Astronauts describe seeing Earth from space as transformative, I think VR could democratize this."),
    ("opinion on", "slow fashion", "Buying fewer, higher quality garments is better for the planet and your wallet long-term."),
    ("favorite", "method for sharpening chisels", "Scary sharp method with progressively finer sandpaper on glass, it's cheap and effective."),
    ("take on", "the streetlight effect in research", "We study what's easy to measure rather than what matters, and it distorts entire fields."),
    ("opinion on", "citizen science projects", "eBird and Galaxy Zoo show that amateurs can contribute meaningfully to real research."),
    ("favorite", "type of sundial", "Equatorial sundials, the hour lines are evenly spaced which makes them the most accurate."),
    ("take on", "deep time", "Thinking in millions of years makes human concerns feel small but our potential feel vast."),
    ("opinion on", "biomimetic robotics", "Boston Dynamics' robots move like animals because evolution already optimized for locomotion."),
    ("favorite", "paradox in economics", "The diamond-water paradox, water is more useful but diamonds are more expensive because of marginal utility."),
    ("take on", "the tragedy of the commons", "It's the best framework for understanding climate change and why individual action isn't enough."),
    ("opinion on", "sensory gardens for therapy", "Designing gardens around all five senses helps with anxiety, dementia, and rehabilitation."),
    ("favorite", "application of Markov chains", "Text generation from Markov chains was my first AI project and it taught me the fundamentals."),
    ("take on", "technological unemployment", "AI will displace jobs faster than new ones are created in the short term, and we need to prepare."),
    ("opinion on", "forest bathing (shinrin-yoku)", "The Japanese practice of simply being present in a forest measurably reduces cortisol levels."),
    ("favorite", "type of traditional dance", "Argentine tango, the connection between partners and the musicality is unmatched."),
    ("take on", "the Cobra effect", "Incentives that backfire are everywhere in policy, it's a lesson in second-order thinking."),
    ("opinion on", "cyanotype photography", "Sun printing with iron salts creates stunning blue-and-white images from any negative."),
    ("favorite", "type of puzzle", "Cryptic crosswords, they're a completely different skill from standard crosswords and deeply satisfying."),
    ("take on", "the McNamara fallacy", "Measuring only what's quantifiable and ignoring the rest leads to terrible decisions."),
    ("opinion on", "handmade paper", "Pulling a sheet of cotton rag paper from a mould is one of those crafts that connects you to history."),
    ("favorite", "application of spectroscopy", "Astronomers determining star composition from light alone is one of science's most powerful tricks."),
    ("take on", "the Overton window", "Understanding what ideas are politically acceptable at any moment explains shifts in public discourse."),
    ("opinion on", "wabi-sabi aesthetics", "Finding beauty in imperfection and impermanence changed how I approach design and life."),
    ("favorite", "type of traditional textile", "Ikat weaving, the dye-resist technique creates beautifully blurred patterns unique to each piece."),
    ("take on", "the map-territory relation", "The map is not the territory, all models are simplifications and we forget that at our peril."),
    ("opinion on", "guerrilla gardening", "Planting flowers in neglected urban spaces is a small act of resistance that beautifies communities."),
    ("favorite", "historical mathematical manuscript", "Ramanujan's notebooks, his intuition produced results that took decades for others to prove."),
    ("take on", "the paradox of tolerance", "A tolerant society must be intolerant of intolerance, Popper got this exactly right."),
    ("opinion on", "dry stone walling", "Building walls without mortar that last centuries is engineering through pure craft."),
    ("favorite", "type of traditional medicine practice", "Acupuncture for chronic pain, the mechanisms aren't fully understood but the clinical evidence is real."),
    ("take on", "the Anna Karenina principle", "Happy families are alike but every unhappy family is unhappy in its own way applies to so many systems."),
    ("opinion on", "acoustic ecology", "Paying attention to soundscapes and protecting natural quiet zones is an undervalued conservation goal."),
    ("favorite", "type of moss for terrariums", "Sheet moss for ground cover and mood moss for texture, together they create a miniature forest."),
    ("take on", "the Lindy effect", "Things that have survived a long time will likely survive proportionally longer, which guides my reading choices."),
    ("opinion on", "Japanese woodblock printing (ukiyo-e)", "The registration system for multi-color prints is ingenious and Hokusai's Great Wave is iconic for a reason."),
    ("favorite", "type of renewable energy technology", "Offshore wind turbines, the engineering challenges are enormous but the energy output is massive."),
    ("take on", "the Easterlin paradox", "Beyond a threshold, more income doesn't increase happiness, which suggests we chase the wrong metrics."),
    ("opinion on", "biophilic design in architecture", "Integrating natural elements into buildings measurably improves occupant well-being and productivity."),
    ("favorite", "type of traditional pottery technique", "Raku firing, pulling glowing pieces from the kiln and reducing them in combustible material creates unrepeatable glazes."),
    ("take on", "the Jevons paradox", "Making resource use more efficient often increases total consumption, which is counterintuitive and important for climate policy."),
    ("opinion on", "amateur astronomy", "A good pair of binoculars and a star chart can show you Jupiter's moons from your backyard."),
    ("favorite", "type of hand tool", "A well-tuned hand plane, the whisper of a thin shaving curling off the blade is deeply satisfying."),
    ("take on", "the peak-end rule in psychology", "We judge experiences by their peak intensity and ending, not the average, which has huge UX implications."),
    ("opinion on", "food preservation through lacto-fermentation", "Sauerkraut, kimchi, and pickles are all the same basic technique and they transform vegetables into something magical."),
    ("favorite", "obscure programming concept", "Monads, once you understand them you see the pattern everywhere from error handling to async."),
    ("take on", "the paradox of hedonism", "Directly pursuing pleasure makes it harder to achieve, the best experiences come as byproducts of meaningful activity."),
    ("opinion on", "traditional Japanese paper (washi)", "Kozo fiber washi is strong enough to use for bookbinding and beautiful enough to frame."),
    ("favorite", "type of scientific instrument", "The electron microscope, seeing individual atoms still feels like science fiction made real."),
    ("take on", "Chesterton's fence", "Before removing a rule or institution, understand why it was put there in the first place."),
    ("opinion on", "phenology and nature journaling", "Recording when plants bloom and birds arrive year after year reveals climate change in your own backyard."),
    ("favorite", "type of historical map", "Portolan charts from medieval sailors, the accuracy of coastlines drawn from dead reckoning is remarkable."),
    ("take on", "the sunk cost fallacy", "Learning to walk away from bad investments of time and money was one of the hardest but best skills I developed."),
    ("opinion on", "traditional dyeing with cochineal", "The vibrant red from crushed insects has been used for centuries and the color is absolutely stunning."),
    ("favorite", "type of optical illusion", "The Necker cube, the way your brain flips between two interpretations demonstrates perceptual ambiguity."),
    ("take on", "the Streisand effect", "Trying to suppress information online almost always amplifies it, which should inform every PR strategy."),
    ("opinion on", "microbial terroir in food production", "The specific microbes in a region's air and water give cheese, wine, and bread their unique character."),
    ("favorite", "theorem in probability", "Bayes' theorem, updating beliefs with new evidence is the foundation of rational thinking."),
    ("take on", "the curse of knowledge", "Once you know something, it's nearly impossible to imagine not knowing it, which makes teaching hard."),
    ("opinion on", "digital minimalism", "Cal Newport's framework of being intentional about technology use improved my focus and well-being."),
    ("favorite", "type of weather phenomenon", "Mammatus clouds, the bubble-like formations before storms look like the sky is upside down."),
    ("take on", "Goodhart's law", "When a measure becomes a target, it ceases to be a good measure, this explains most institutional dysfunction."),
    ("opinion on", "traditional fermented dairy", "Kefir grains passed down through generations produce a probiotic drink that commercial yogurt can't match."),
    ("favorite", "thought experiment in philosophy", "The veil of ignorance, designing society without knowing your position in it leads to fairer systems."),
    ("take on", "the availability heuristic", "We overestimate the probability of events we can easily remember, which distorts risk perception."),
    ("opinion on", "parametric design in architecture", "Using algorithms to generate building forms creates structures that would be impossible to design by hand."),
    ("favorite", "type of folk music tradition", "Appalachian old-time fiddle music, the modal tunings and driving rhythm are infectious."),
    ("take on", "the cobra effect in software engineering", "Paying developers by lines of code written is the perfect example of incentivizing the wrong metric."),
    ("opinion on", "biomineralization", "Organisms building shells, bones, and teeth from dissolved minerals is nanotechnology that nature perfected."),
    ("favorite", "example of mathematical art", "Escher's tessellations, the way he translated hyperbolic geometry into visual art is brilliant."),
    ("take on", "the framing effect in decision making", "Presenting the same information differently changes choices, which has massive implications for policy design."),
    ("opinion on", "heritage grain cultivation", "Ancient wheat varieties like emmer and einkorn taste better and are more nutritious than modern cultivars."),
    ("favorite", "type of celestial event", "Total solar eclipses, experiencing totality is genuinely one of the most profound things a human can witness."),
    ("take on", "the principle of charity in argumentation", "Always interpret someone's argument in its strongest form before responding, it leads to better discourse."),
    ("opinion on", "traditional boat building", "Clinker-built boats with overlapping planks are beautiful, seaworthy, and a testament to Viking engineering."),
    ("favorite", "type of philosophical razor", "Occam's razor, the simplest explanation that fits the evidence is usually correct."),
    ("take on", "the spotlight effect", "We think people notice our mistakes far more than they actually do, which should liberate us."),
    ("opinion on", "agroforestry", "Integrating trees with crops mimics natural ecosystems and produces more per acre than monoculture."),
    ("favorite", "example of mathematical recreation", "The four-color theorem, it was the first major theorem proved with computer assistance and sparked debate."),
    ("take on", "loss aversion in behavioral economics", "Losing $100 hurts twice as much as gaining $100 feels good, and this asymmetry shapes most decisions."),
    ("opinion on", "traditional glassblowing", "Watching a gather of molten glass become a vessel in minutes is hypnotic and the skill ceiling is infinite."),
    ("favorite", "type of planetary feature", "Saturn's hexagonal storm at its north pole, a geometric weather pattern on a gas giant is surreal."),
    ("take on", "the doorway effect on memory", "Walking through doorways causes forgetting because our brains segment experience by location."),
    ("opinion on", "craftsman-style architecture", "Exposed joinery, natural materials, and handmade details create homes that feel alive and honest."),
    ("favorite", "type of mathematical proof style", "Visual proofs, a well-drawn diagram can make a theorem obvious in ways algebra never could."),
    ("take on", "the backfire effect", "Presenting evidence against someone's beliefs can make them hold those beliefs more strongly, which complicates everything."),
    ("opinion on", "natural building with cob", "Sculpting walls from earth, sand, and straw creates organic forms that no other building method allows."),
    ("favorite", "application of differential equations", "Modeling population dynamics with Lotka-Volterra equations shows how predator and prey populations oscillate."),
    ("take on", "the status quo bias", "We prefer things to stay the same even when change would benefit us, and recognizing this helps with decisions."),
    ("opinion on", "heritage seed libraries", "Community seed banks preserve genetic diversity that industrial agriculture is rapidly destroying."),
    ("favorite", "type of ancient technology", "The Antikythera mechanism, an analog computer from 100 BC that predicted eclipses and planetary positions."),
    ("take on", "Weber's law of just noticeable difference", "The fact that perception scales logarithmically explains everything from audio mixing to pricing psychology."),
    ("opinion on", "traditional charcoal making", "Japanese binchōtan charcoal burns cleaner and longer than any briquette, the firing process takes days."),
    ("favorite", "type of scientific visualization", "Phase space diagrams, seeing a system's entire behavior space in one plot reveals structure that equations hide."),
    ("take on", "the IKEA effect", "We overvalue things we build ourselves, which explains why participatory design creates more engaged users."),
    ("opinion on", "acoustic guitar building", "Bending sides, carving braces, and choosing tonewoods results in an instrument that sounds like nothing else."),
    ("favorite", "extinct animal", "Thylacine, the Tasmanian tiger's convergent evolution with canines from a marsupial lineage is remarkable."),
    ("take on", "counterfactual thinking", "Imagining how things could have been different is essential for learning but dangerous for happiness."),
    ("opinion on", "Persian carpet weaving", "A single handwoven carpet can take years and contain millions of knots, it's art at the scale of patience."),
    ("favorite", "type of symbiotic relationship", "Mycorrhizal networks between trees, the wood wide web of fungal connections sharing nutrients underground."),
    ("take on", "the narrative fallacy", "We impose stories on random events to make sense of them, which helps psychologically but distorts analysis."),
    ("opinion on", "earth-sheltered architecture", "Building into hillsides provides natural insulation, storm protection, and a minimal visual footprint."),
    ("favorite", "type of mathematical space", "Hyperbolic space, where parallel lines diverge and triangles have angles summing to less than 180 degrees."),
    ("take on", "anchoring in negotiations", "The first number on the table disproportionately influences the outcome, which is why I always name my price first."),
    ("opinion on", "traditional salt harvesting", "Solar evaporation salt pans produce fleur de sel that tastes of the sea in a way industrial salt never will."),
    ("favorite", "type of migratory pattern", "Arctic terns flying pole to pole, experiencing two summers per year and the most daylight of any creature."),
    ("take on", "the Pygmalion effect", "Higher expectations literally produce better performance, which transforms how I think about teaching and management."),
    ("opinion on", "hand-forged blacksmithing", "Shaping hot metal with a hammer connects you to a craft that's essentially unchanged for thousands of years."),
    ("favorite", "mathematical conjecture", "The twin prime conjecture, that there are infinitely many primes differing by 2, is simple to state and deeply mysterious."),
    ("take on", "the bystander effect", "Diffusion of responsibility in groups means you should always point to a specific person when asking for help."),
    ("opinion on", "permaculture food forests", "Layered planting that mimics forest ecology can produce food with minimal maintenance once established."),
    ("favorite", "type of historical preservation technique", "Dendrochronology, dating wooden structures by tree ring patterns gives exact years without destroying the artifact."),
    ("take on", "the decoy effect in marketing", "Adding a third inferior option makes one of the original two seem more attractive, and it works every time."),
    ("opinion on", "Japanese fish printing (gyotaku)", "Inking an actual fish and pressing it to paper creates scientific records that are also beautiful art."),
    ("favorite", "type of wave phenomenon", "Standing waves on a Chladni plate, sand forming geometric patterns from vibration is mesmerizing."),
    ("take on", "the endowment effect", "Owning something makes us value it more, which explains why decluttering is psychologically difficult."),
    ("opinion on", "rocket mass heaters", "Burning wood at extremely high temperatures with thermal mass storage is the most efficient wood heating system."),
]


def build_extra_qa(extras: list[tuple], start_idx: int) -> list[tuple[str, str]]:
    pairs = []
    for kind, topic, answer in extras:
        question = f"What's your {kind} {topic}?"
        if kind == "opinion on":
            question = f"What's your opinion on {topic}?"
        elif kind == "take on":
            question = f"What's your take on {topic}?"
        pairs.append((question, answer))
    return pairs


def generate_niche_data() -> dict:
    all_qa = list(QA_PAIRS)
    extras = build_extra_qa(EXTRA_TOPICS, len(all_qa))
    all_qa.extend(extras)

    entries = []
    for i, (q, a) in enumerate(all_qa):
        entries.append({"id": i, "question": q, "answer": a})

    return {"total": len(entries), "qa_pairs": entries}


if __name__ == "__main__":
    data = generate_niche_data()
    with open("niche_questions.json", "w") as f:
        json.dump(data, f, indent=2)
    print(f"Generated {data['total']} unique Q/A pairs.")
