"""Generate 1000 unique one-sentence answer sets for 5 political questions."""

import json
import random

random.seed(42)

QUESTIONS = [
    "Do you believe the government should take an active role in solving social problems, or should individuals and private organizations handle them?",
    "Which is more important to you: economic growth even if it increases inequality, or reducing inequality even if it slows growth?",
    "Should society prioritize preserving traditional values or adapting to changing social norms?",
    "How urgent is it for governments to take strong action against climate change?",
    "Do you think a country should focus more on global cooperation or prioritize national interests?",
]

# --- Q1: Role of Government ---
q1_templates = [
    "Government has a responsibility to step in when markets and individuals fail.",
    "Private organizations and communities are usually more effective than government programs.",
    "Government should focus on infrastructure and rules, not direct solutions.",
    "Some problems are too big for individuals—only collective action through government can fix them.",
    "Charities and nonprofits often do better work than government bureaucracy.",
    "Government intervention is sometimes necessary to protect the vulnerable.",
    "I prefer local and voluntary solutions over federal mandates.",
    "Government should create the conditions for prosperity, then step back.",
    "Without government action, the free market leaves too many people behind.",
    "The best government is one that empowers people to solve their own problems.",
    "Government programs have a track record of unintended consequences.",
    "We need strong government for things like healthcare and retirement security.",
    "Communities know their own needs better than any agency in Washington.",
    "Government has a moral duty to reduce poverty and inequality.",
    "Regulation often does more harm than good.",
    "Some problems—like climate change—require government leadership.",
    "I trust markets more than politicians to allocate resources.",
    "Government should ensure a floor below which no one falls.",
    "Faith-based and community organizations often outperform government.",
    "We need government to level the playing field for everyone.",
    "Government overreach has eroded personal freedom.",
    "Collaboration between government and private sector is ideal.",
    "Government should only act when there's clear market failure.",
    "A strong safety net prevents people from falling through the cracks.",
    "The private sector innovates faster than government ever could.",
    "Government has a role in education, healthcare, and housing.",
    "I'd rather have more local control and less federal involvement.",
    "Government programs can be effective when well-designed and funded.",
    "Voluntary cooperation beats forced redistribution.",
    "We need government to protect workers and consumers from abuse.",
    "Government often makes problems worse by trying to fix them.",
    "Some services—like roads and defense—only government can provide well.",
    "Mutual aid networks and cooperatives can replace many government functions.",
    "Government should invest in research and development the private sector won't fund.",
    "Too much government dependency undermines self-reliance.",
    "Government is necessary to rein in corporate power.",
    "I believe in a mixed approach depending on the specific problem.",
    "Government should focus on justice and opportunity, not handouts.",
    "Private charity is more dignified than government assistance.",
    "We need government to ensure everyone has access to basic necessities.",
    "Government bureaucracy wastes resources that could help people directly.",
    "The best approach is government setting goals and letting local actors implement.",
    "Government has failed too often for me to trust it with more responsibility.",
    "We need both—government for scale, civil society for flexibility.",
    "Government should provide a baseline so everyone can pursue their goals.",
    "Decentralized solutions are almost always better than top-down mandates.",
    "Government intervention is justified when it protects human dignity.",
    "I support government action in emergencies and crises.",
    "The private sector will innovate solutions if we remove barriers.",
    "Government's role is to protect rights, not to solve every problem.",
    "We need smart regulation that doesn't stifle innovation.",
    "Government has helped in the past—Social Security, Medicare—and can again.",
    "I prefer solutions that respect both individual freedom and collective need.",
    "Government should fill gaps the market doesn't serve.",
    "Too often government picks winners and losers unfairly.",
    "Strong institutions require government investment and oversight.",
    "I'd rather err on the side of less government than more.",
    "Government should act when the market creates systemic harms.",
    "Civil society and family are the first line of defense.",
    "We need government to enforce contracts and property rights fairly.",
    "Some problems require collective sacrifice only government can coordinate.",
    "Government programs have lifted millions out of poverty.",
    "I trust state and local government more than federal.",
    "Government should ensure competition rather than control outcomes.",
    "The answer depends on whether we're talking about healthcare, housing, or education.",
    "Government has a role but it should be limited and targeted.",
    "We need government to protect the environment for future generations.",
    "Private solutions often exclude the poorest and most vulnerable.",
    "Government should invest in people through education and training.",
    "I believe in subsidiarity—solve problems at the lowest level possible.",
    "Government can be a force for good when it's accountable and transparent.",
    "The best government empowers citizens to build their own solutions.",
]

# --- Q2: Economic Priorities ---
q2_templates = [
    "Economic growth lifts everyone over time—we should prioritize it.",
    "Reducing inequality matters more; growth without fairness is empty.",
    "We can have both—smart policy can promote growth and reduce inequality.",
    "Growth creates opportunities; equality of opportunity matters more than outcome.",
    "Extreme inequality undermines democracy and social cohesion.",
    "A rising tide lifts all boats, but some boats need help staying afloat.",
    "I'd accept slower growth if it meant fewer people in poverty.",
    "Growth without redistribution leaves too many people behind.",
    "Entrepreneurship and innovation require the incentive of inequality.",
    "The gap between rich and poor has grown too large to ignore.",
    "Economic freedom leads to growth that benefits everyone eventually.",
    "We need a balance—neither pure capitalism nor pure redistribution.",
    "Trickle-down economics hasn't worked; we need different priorities.",
    "Growth is how we fund programs that help the needy.",
    "Inequality of wealth is less important than mobility and opportunity.",
    "Concentrated wealth leads to concentrated power, which corrupts.",
    "Tax policy should favor growth while protecting the vulnerable.",
    "The middle class has been hollowed out; we need to fix that.",
    "Reward success, but don't let the bottom fall out.",
    "Structural inequality requires structural solutions.",
    "Markets allocate efficiently but don't distribute fairly.",
    "Growth that only benefits the top is growth we can do without.",
    "People who take risks deserve to reap rewards.",
    "Childhood poverty affects lifetime outcomes—we must address it.",
    "Economic dynamism requires some inequality as incentive.",
    "We should measure success by how the poorest are doing.",
    "A strong middle class drives sustainable growth.",
    "Redistribution disincentivizes work and innovation.",
    "We need living wages and strong labor protections.",
    "Capital gains and inheritance create unfair advantages.",
    "Growth creates jobs; jobs reduce poverty.",
    "The minimum wage should be a living wage.",
    "We've tried growth-first; it's time to try fairness-first.",
    "Both matter—but right now inequality is the crisis.",
    "Entrepreneurs create jobs; we should reward that.",
    "Healthcare and education shouldn't depend on wealth.",
    "We need antitrust to prevent monopoly power.",
    "Growth without environmental sustainability is short-sighted.",
    "Everyone deserves a chance to build wealth.",
    "The wealthiest should pay a larger share—they benefit most from society.",
    "Property rights and free exchange are the foundation of prosperity.",
    "Intergenerational poverty is a policy failure we can fix.",
    "Competition drives growth; we should foster it.",
    "We need universal basic services before we worry about growth.",
    "Growth metrics like GDP miss distributional effects.",
    "Fair taxation can fund both growth investments and safety nets.",
    "I care more about absolute poverty than relative inequality.",
    "Worker ownership and profit-sharing can align incentives.",
    "Growth has left too many communities behind.",
    "We need investment in human capital for long-term growth.",
    "The answer isn't either-or; it's finding the right mix.",
    "Corporate profits have grown while wages stagnated—that's wrong.",
    "Economic security enables people to take risks and innovate.",
    "We should prioritize both—they're not mutually exclusive.",
    "Historical growth came with union power and progressive taxation.",
    "Mobility matters more than snapshot inequality.",
    "We need to make work pay again.",
    "Growth that destroys the planet isn't real growth.",
    "Reducing inequality can actually spur growth by increasing demand.",
    "I believe in opportunity, not guaranteed outcomes.",
    "The data shows growth alone hasn't reduced poverty enough.",
    "We should experiment with policies and follow the evidence.",
]

# --- Q3: Social Change and Tradition ---
q3_templates = [
    "Tradition provides stability; we shouldn't discard it lightly.",
    "Society must evolve; clinging to the past holds us back.",
    "Some traditions are worth keeping, others we've outgrown.",
    "Traditional values like family and community are the foundation of society.",
    "Change is constant; resisting it is futile and often harmful.",
    "We should preserve what works and adapt what doesn't.",
    "Many traditions excluded or harmed people; we need to acknowledge that.",
    "Tradition gives meaning and continuity across generations.",
    "Social norms have changed for the better—we should keep pushing.",
    "The pace of change has been too fast; we need to slow down.",
    "Tradition without critical examination becomes oppression.",
    "Community standards should be set locally, not imposed from outside.",
    "We've made progress on rights; we shouldn't reverse it.",
    "Traditional institutions like marriage and religion still serve people.",
    "Society should accommodate diverse ways of life.",
    "We've lost something valuable in our rush to modernize.",
    "Change should be gradual and respectful of those who need time to adjust.",
    "Some things are timeless—honesty, compassion, hard work.",
    "We need to update our values for a more interconnected world.",
    "Tradition provides identity in an increasingly rootless society.",
    "The young shouldn't dismiss the wisdom of elders.",
    "We've expanded who counts as fully human—that's progress.",
    "Traditional gender roles served a purpose; we need new models.",
    "LGBTQ+ rights and racial equality are non-negotiable achievements.",
    "We should be careful what we tear down—we might need it later.",
    "Inclusive societies are stronger and more resilient.",
    "Some traditions are worth reviving—civic engagement, local community.",
    "Technology and globalization require new norms.",
    "We can honor the past without being bound by it.",
    "The arc of history bends toward justice—we should help it along.",
    "Too much change too fast creates anxiety and backlash.",
    "Multiculturalism enriches society; we should embrace it.",
    "Traditional family structures provided support we've lost.",
    "We need norms that work for diverse family arrangements.",
    "Religious freedom matters, but so does equality for all.",
    "We've become too individualistic; we need to rebuild community.",
    "Progress isn't linear—we should learn from past mistakes.",
    "Local cultures and languages are worth preserving.",
    "Universal human rights transcend any single tradition.",
    "We need a balance between continuity and progress.",
    "Traditions that harm people have no claim on our loyalty.",
    "We should listen to those who feel left behind by change.",
    "Identity is complicated; we should make room for complexity.",
    "The best traditions are ones that include more people over time.",
    "Change is scary; we need empathy for those struggling with it.",
    "We can build new traditions that reflect our values today.",
    "Some change is necessary; some is just fashion.",
    "We should be humble about what we think we know.",
    "Tradition and progress aren't opposites—they inform each other.",
    "We've made real progress; we shouldn't take it for granted.",
    "The goal is a society where everyone can flourish.",
    "We need dialogue between generations and cultures.",
    "Values like dignity and respect apply to everyone.",
    "We should preserve what's good and reform what isn't.",
]

# --- Q4: Climate and Environment ---
q4_templates = [
    "It's an emergency—we need massive government action now.",
    "It's important but we should balance environmental goals with economic reality.",
    "Climate change is the defining challenge of our generation.",
    "We need to act, but through innovation, not heavy-handed regulation.",
    "The science is clear; delay makes everything harder and more expensive.",
    "Different countries have different responsibilities—we need fair burden-sharing.",
    "Renewable energy is now economically viable; we should accelerate the transition.",
    "We can't destroy jobs and industry in the name of climate action.",
    "Climate change disproportionately harms the poorest—that's a moral imperative.",
    "Technology will solve this; we need to invest in R&D.",
    "We've already passed tipping points; adaptation matters as much as mitigation.",
    "Carbon pricing is the most efficient way to reduce emissions.",
    "The urgency is real but so are the costs of rapid transition.",
    "Young people will bear the brunt—we owe them action.",
    "We should focus on nuclear and natural gas as bridges.",
    "Every year we wait, the required changes get more drastic.",
    "Industry needs certainty and incentives, not just regulations.",
    "Developing countries need support to green their economies.",
    "Climate action can create jobs if we do it right.",
    "We can't unilaterally disarm our economy while others pollute.",
    "The transition must be just—workers in fossil fuels need retraining.",
    "Renewable subsidies have distorted markets; we need a level playing field.",
    "Biodiversity loss is as urgent as climate change.",
    "We need both mitigation and adaptation—it's not either-or.",
    "Government should set ambitious targets and let markets find solutions.",
    "Individual choices matter but systemic change matters more.",
    "We've made progress; we need to accelerate it.",
    "Energy independence through renewables is a national security issue.",
    "The costs of inaction far exceed the costs of action.",
    "We should leverage private capital for the green transition.",
    "Climate refugees will be a major challenge—we need to prepare.",
    "Farming and land use are underrated parts of the solution.",
    "We need to be honest about tradeoffs—no solution is painless.",
    "International cooperation is essential; no country can solve this alone.",
    "Local environmental issues—air quality, water—affect people daily.",
    "We've been kicking the can; future generations will pay.",
    "Innovation in batteries and grid storage will be decisive.",
    "The green transition should not increase inequality.",
    "We need to protect natural carbon sinks—forests, wetlands.",
    "Climate skepticism has delayed action we can't afford.",
    "Different regions need different solutions—one size doesn't fit all.",
    "We should invest in resilience to inevitable changes.",
    "The market will drive change once the externalities are priced.",
    "Urgency doesn't mean panic—we need thoughtful, sustained action.",
    "Fossil fuel companies should help fund the transition.",
    "Conservation and restoration are undervalued tools.",
    "We need to decarbonize without deindustrializing.",
    "The window for limiting warming to 1.5°C is narrowing.",
    "Climate action and economic development can go together.",
    "We should learn from countries that have decarbonized successfully.",
    "The status quo is not an option.",
]

# --- Q5: Global vs. Local Focus ---
q5_templates = [
    "National interests should come first—we have to take care of our own.",
    "Global problems require global cooperation; isolation won't work.",
    "We need both—strong at home, engaged abroad.",
    "Protectionism and nationalism have historically led to conflict.",
    "Our prosperity depends on global trade and alliances.",
    "We should focus on fixing our domestic problems before intervening abroad.",
    "Climate, pandemics, and migration don't respect borders.",
    "Other countries will fill the vacuum if we retreat.",
    "Too much foreign involvement has drained resources from home.",
    "International institutions need reform, not abandonment.",
    "We owe it to our allies to maintain our commitments.",
    "Economic nationalism hurts consumers and workers long-term.",
    "Immigration has been a source of strength; we should uphold that.",
    "We need to be more selective about where we invest globally.",
    "Global supply chains make us vulnerable—we need resilience.",
    "Human rights are universal; we have a stake in promoting them.",
    "We can't solve every world problem; we need to prioritize.",
    "NATO and alliances have kept the peace for decades.",
    "Fair trade is more important than free trade.",
    "Refugees and migrants deserve compassion and orderly processes.",
    "We need to compete with China, not isolate ourselves.",
    "Foreign aid can be effective when well-designed.",
    "Sovereignty matters; we shouldn't outsource decisions to international bodies.",
    "Global health and disease surveillance require cooperation.",
    "We've overextended ourselves militarily; it's time to recalibrate.",
    "Multilateral agreements are imperfect but better than go-it-alone.",
    "We should lead by example rather than lecture others.",
    "Cyber threats and terrorism require international coordination.",
    "The UN has flaws but remains necessary.",
    "We need to rebuild manufacturing at home for security.",
    "Democracies should stick together against authoritarianism.",
    "Offshoring jobs hurt American workers—we need better trade deals.",
    "We can't turn our back on allies who depend on us.",
    "Immigration policy should serve national interests and humanitarian values.",
    "Global institutions reflect power from 1945; they need updating.",
    "We should focus on the hemisphere before distant regions.",
    "International law provides a framework we should strengthen.",
    "Economic interdependence reduces the chance of war.",
    "We need to balance engagement with realism about our limits.",
    "Development abroad can reduce migration pressure and create markets.",
    "Patriotic doesn't mean isolationist.",
    "We have interests and values—both matter in foreign policy.",
    "Regional organizations can sometimes do what global ones can't.",
    "We should invest in diplomacy before military options.",
    "Supply chain diversification reduces risk.",
    "We can't go it alone on climate, health, or security.",
    "Nationalism has legitimate concerns we should address.",
    "Smart engagement advances our interests and values.",
    "We need to listen to other countries, not just dictate.",
    "The world is interconnected whether we like it or not.",
    "Prioritizing national interests doesn't mean ignoring the world.",
    "We should support democracies and human rights without imposing.",
    "Trade wars hurt everyone; we need rules-based cooperation.",
    "Our military presence abroad has costs and benefits we should weigh honestly.",
    "We need alliances to counter authoritarian expansion.",
    "A prosperous world is better for everyone, including us.",
    "We should engage where we can make a difference and be humble about limits.",
]


def generate_answers(n: int = 1000) -> list[dict]:
    data = []
    for i in range(n):
        entry = {
            "id": i,
            "answers": {
                "q1_role_of_government": q1_templates[i % len(q1_templates)],
                "q2_economic_priorities": q2_templates[i % len(q2_templates)],
                "q3_social_change_tradition": q3_templates[i % len(q3_templates)],
                "q4_climate_environment": q4_templates[i % len(q4_templates)],
                "q5_global_vs_local": q5_templates[i % len(q5_templates)],
            },
        }
        data.append(entry)
    return data


if __name__ == "__main__":
    result = {
        "questions": QUESTIONS,
        "responses": generate_answers(1000),
    }
    with open("political_answers.json", "w") as f:
        json.dump(result, f, indent=2)
    print(f"Generated {len(result['responses'])} answer sets.")
