"""Generate 500+ unique political questions from broad to niche, each with a 1-2 sentence answer."""

import json
import random

random.seed(99)

QA_PAIRS = [
    # --- BROAD POLITICAL (1-80) ---
    ("How should we balance free speech with protecting people from harmful content?", "I believe in strong free speech but platforms have a responsibility to curb genuine harm and misinformation."),
    ("What's your view on the size and scope of the military?", "We need a strong defense but should focus on efficiency and avoid unnecessary interventions abroad."),
    ("Should voting be mandatory?", "No—civic duty matters but forcing people to vote could lead to uninformed choices; we should make voting easier instead."),
    ("What's your stance on term limits for elected officials?", "I support term limits for Congress—fresh perspectives prevent entrenched power and corruption."),
    ("How do you feel about the electoral college?", "It's outdated and distorts democracy; we should move toward popular vote or proportional allocation."),
    ("What's your view on campaign finance reform?", "Money in politics corrupts outcomes; we need stricter limits and public financing for elections."),
    ("Should the Supreme Court be expanded or reformed?", "Expansion feels like court-packing; I'd prefer term limits and ethical codes for justices."),
    ("What's your take on federalism—states' rights vs. federal power?", "Some issues need national standards, others are better handled locally; it depends on the issue."),
    ("How do you feel about direct democracy (referendums, initiatives)?", "Useful for big questions but voters can't become experts on everything—representative democracy has a role."),
    ("What's your view on the two-party system?", "It's broken—ranked-choice voting and multi-party coalitions would represent people better."),
    ("Should we have a national popular vote for president?", "Yes, every vote should count equally regardless of where you live."),
    ("What's your stance on lobbying?", "Some lobbying informs policy; the problem is money and access, not advocacy itself."),
    ("How do you feel about voter ID laws?", "They sound reasonable but data shows they suppress turnout; we should make voting easier, not harder."),
    ("What's your take on the filibuster?", "It was meant for rare cases; now it blocks everything—reform or eliminate it."),
    ("How important is civic education?", "Critical—people can't participate meaningfully without understanding how government works."),
    ("What's your view on political polarization?", "It's a real problem; we need institutions that reward compromise and penalize extremism."),
    ("Should we lower the voting age?", "Maybe to 16 for local elections—young people are affected by policy and deserve a voice."),
    ("What's your stance on gerrymandering?", "We need independent commissions; politicians shouldn't choose their voters."),
    ("How do you feel about executive orders?", "Necessary for urgent action but overused—Congress should do its job instead."),
    ("What's your take on political dynasties?", "Families in politics aren't inherently bad, but we need more diverse representation."),
    # --- ECONOMIC POLICY (21-100) ---
    ("What's your view on the minimum wage?", "It should be a living wage indexed to inflation; businesses adapt when we've raised it before."),
    ("Should we have a universal basic income?", "Worth piloting—automation may displace workers and we need a floor."),
    ("What's your stance on raising taxes on the wealthy?", "The top marginal rates were much higher historically; we can raise them without harming growth."),
    ("How do you feel about antitrust enforcement?", "We've been too lenient; big tech and other consolidations hurt competition and consumers."),
    ("What's your take on universal healthcare?", "Healthcare is a right; single-payer or strong public option would reduce costs and cover everyone."),
    ("Should student debt be forgiven?", "Some forgiveness is justified—predatory lending and wage stagnation made repayment impossible for many."),
    ("What's your view on unions and collective bargaining?", "Unions built the middle class; we need stronger protections for organizing."),
    ("How do you feel about free trade agreements?", "Trade creates wealth but we need better safety nets for displaced workers."),
    ("What's your stance on the federal deficit?", "Important long-term but we underinvest in infrastructure and R&D; borrowing for investment makes sense."),
    ("Should we break up the big banks?", "Some of them are too big to fail—we need either breakup or much tougher regulation."),
    ("What's your take on rent control?", "It helps some tenants but reduces supply; we need more housing construction, not just control."),
    ("How do you feel about tariffs?", "Usually counterproductive—they raise prices and invite retaliation."),
    ("What's your view on paid parental leave?", "Essential—every developed country has it and we're behind."),
    ("Should we expand Social Security?", "Yes—people have paid in; benefits should keep pace with need."),
    ("What's your stance on crypto and digital currency regulation?", "Innovation is real but we need consumer protection and to prevent fraud."),
    ("How do you feel about subsidies for renewable energy?", "Necessary to accelerate the transition; fossil fuels got subsidies for decades."),
    ("What's your take on the gig economy and worker classification?", "Many gig workers are effectively employees and deserve benefits; the law should reflect that."),
    ("Should the Fed have a dual mandate (employment + inflation)?", "Yes—focusing only on inflation ignores real harm from unemployment."),
    ("What's your view on estate taxes?", "Inherited wealth entrenches inequality; a strong estate tax is fair."),
    ("How do you feel about occupational licensing?", "Some licensing protects public safety; many requirements are barriers to entry that hurt workers."),
    # --- SOCIAL POLICY (41-120) ---
    ("What's your stance on abortion rights?", "A woman's right to choose is fundamental; government shouldn't dictate personal medical decisions."),
    ("How do you feel about the death penalty?", "I oppose it—irreversible, applied unfairly, and the state shouldn't have that power."),
    ("What's your view on drug legalization or decriminalization?", "Portugal's approach works—decriminalize, treat addiction as health issue, legalize marijuana."),
    ("Should we have stricter gun control?", "Yes—background checks, red flag laws, and limits on weapons of war save lives."),
    ("What's your take on the war on drugs?", "It's failed—mass incarceration, racial disparity, and it hasn't reduced drug use."),
    ("How do you feel about LGBTQ+ rights?", "Full equality—marriage, adoption, employment, healthcare—no exceptions."),
    ("What's your stance on religious freedom vs. antidiscrimination?", "Religious freedom matters but can't be used to discriminate against others in public accommodations."),
    ("Should we have mandatory national service?", "Voluntary programs are better; mandatory service raises freedom concerns."),
    ("What's your view on the separation of church and state?", "Essential—government should neither promote nor hinder religion."),
    ("How do you feel about affirmative action?", "Race can be one factor among many; diversity in education and work benefits everyone."),
    ("What's your take on school choice and vouchers?", "Parents deserve options but vouchers can drain public schools; focus on fixing public education first."),
    ("Should we have universal pre-K?", "Yes—the evidence is strong that early education pays dividends."),
    ("What's your stance on standardized testing in schools?", "Some measurement is useful but we've over-relied on tests; they don't capture full learning."),
    ("How do you feel about cancel culture?", "Accountability is good; mob dynamics and permanent shaming can go too far."),
    ("What's your view on hate speech laws?", "The line is hard to draw; I lean toward strong protections for speech with consequences for incitement."),
    ("Should we decriminalize sex work?", "Decriminalization protects workers; criminalization harms the vulnerable."),
    ("What's your take on prison reform?", "We incarcerate too many people; focus on rehabilitation and alternatives for nonviolent offenses."),
    ("How do you feel about the Second Amendment?", "Individual right with reasonable regulation—like every other right in the Constitution."),
    ("What's your stance on assisted death / physician-assisted suicide?", "People with terminal illness should have the choice; safeguards are essential."),
    ("Should we have a pathway to citizenship for undocumented immigrants?", "Yes—most contribute to society; we need a sensible path, not mass deportation."),
    # --- FOREIGN POLICY & IMMIGRATION (61-140) ---
    ("What's your view on U.S. military spending?", "We spend more than the next 10 countries combined; we can maintain security with less."),
    ("How do you feel about NATO?", "Essential for collective defense; we should support allies but encourage them to contribute more."),
    ("What's your stance on foreign aid?", "Effective aid reduces instability and creates markets; we should fund it robustly."),
    ("Should we have open borders?", "No—we need orderly immigration, but we should welcome more legal immigrants."),
    ("What's your take on China as a strategic rival?", "We need to compete on technology and values while managing economic interdependence."),
    ("How do you feel about sanctions as a foreign policy tool?", "Mixed—they can pressure regimes but often harm ordinary people more than leaders."),
    ("What's your view on Israel and Palestine?", "Two-state solution is still the best path; both peoples deserve security and self-determination."),
    ("Should we withdraw from international agreements?", "Engagement is usually better than withdrawal; we lose influence when we leave the table."),
    ("What's your stance on refugee resettlement?", "We have a moral responsibility; our capacity is large—we've done it before."),
    ("How do you feel about nuclear proliferation?", "We should work toward reduction while preventing new nuclear states."),
    ("What's your take on the UN?", "Flawed but necessary; no country can solve global problems alone."),
    ("Should we have a no-first-use nuclear policy?", "Worth considering—reduces existential risk and sets a norm."),
    ("What's your view on military interventions?", "Only with clear objectives, allies, and exit strategy; we've learned costly lessons."),
    ("How do you feel about arms sales to other countries?", "Need case-by-case review; some sales stabilize allies, others fuel conflict."),
    ("What's your stance on the Iran nuclear deal?", "Diplomacy was working; walking away increased risk without gaining leverage."),
    ("How do you feel about immigration enforcement at the border?", "We need order but family separation and harsh tactics are morally wrong."),
    ("What's your take on tariffs on China?", "Targeted pressure can work but broad tariffs hurt American consumers and farmers."),
    ("Should we provide military aid to Ukraine?", "Yes—sovereign nations deserve support against aggression; our interests align."),
    ("What's your view on the Monroe Doctrine?", "Outdated—we should partner with Latin America as equals, not assert hegemony."),
    ("How do you feel about the ICC and international criminal justice?", "Important for accountability; we should support it while pushing for reforms."),
    # --- ENVIRONMENT & CLIMATE (81-160) ---
    ("What's your stance on nuclear power?", "We need it as a bridge—renewables can't fully replace fossil fuels yet."),
    ("How do you feel about the Green New Deal?", "The ambition is right; details matter—we need major investment and jobs in green sectors."),
    ("What's your view on carbon taxes?", "Most economists agree—price carbon and let markets find the most efficient reductions."),
    ("Should we ban fracking?", "Phase it out—we need to transition off fossil fuels, not lock in more infrastructure."),
    ("What's your take on pipeline projects?", "Each case differs; we should weigh climate impact against short-term energy needs."),
    ("How do you feel about protecting public lands?", "Essential—parks, wilderness, and wildlife need federal protection."),
    ("What's your stance on the EPA?", "Critical agency—we need strong environmental regulation backed by science."),
    ("Should we subsidize electric vehicles?", "Yes—we're behind other countries; incentives accelerate adoption."),
    ("What's your view on offshore drilling?", "Risks outweigh benefits; we should transition away, not expand."),
    ("How do you feel about single-use plastic bans?", "Reasonable—reducing waste matters; we need systemic change too."),
    ("What's your take on water rights and allocation?", "Increasingly contentious—we need better frameworks for scarcity."),
    ("Should we have a national recycling program?", "Standardization could help; the real fix is reducing waste and better design."),
    ("What's your stance on endangered species protection?", "We have a moral duty to preserve biodiversity; the ESA has worked."),
    ("How do you feel about factory farming regulation?", "Animal welfare and environmental impact justify stronger regulation."),
    ("What's your view on GMOs?", "Science says they're safe; we should regulate based on evidence, not fear."),
    ("Should we invest in high-speed rail?", "Yes—it reduces emissions and congestion; we're behind other nations."),
    ("What's your take on geoengineering?", "Research it—we may need options if mitigation fails, but governance is crucial."),
    ("How do you feel about energy independence?", "Renewable energy enhances security; fossil fuel independence is the wrong frame."),
    ("What's your stance on deforestation and land use?", "Forests are carbon sinks; we need incentives to protect and restore them."),
    ("Should we have a national climate adaptation plan?", "Yes—some change is locked in; we need to prepare communities."),
    # --- NICHE / SPECIFIC (101-200) ---
    ("What's your view on the Jones Act (maritime shipping)?", "It's protectionist and raises costs; reforming it could help Puerto Rico and reduce prices."),
    ("How do you feel about the filibuster's history and reform?", "It was used to block civil rights; the current 60-vote threshold blocks most legislation."),
    ("What's your stance on qualified immunity for police?", "It shields officers from accountability; we need reform so misconduct has consequences."),
    ("Should we abolish the Department of Education?", "No—federal role in equity and research is valuable; the department could be improved."),
    ("What's your take on the National Popular Vote Interstate Compact?", "Clever way to effectively end the Electoral College without a constitutional amendment."),
    ("How do you feel about the pardon power?", "Necessary for mercy but open to abuse; we need norms and perhaps limits."),
    ("What's your view on DC statehood?", "Residents pay taxes and serve in wars; they deserve representation."),
    ("Should Puerto Rico become a state?", "If Puerto Ricans vote for it—the current territorial status is undemocratic."),
    ("What's your stance on the debt ceiling?", "It's a dangerous political weapon; we should abolish or reform it."),
    ("How do you feel about the Congressional Budget Office?", "Valuable for nonpartisan analysis; we should protect its independence."),
    ("What's your take on fusion energy research?", "Worth investing in—if it works, it could solve energy; we need a diverse portfolio."),
    ("Should we have a wealth tax?", "Implementation is tricky; higher capital gains and inheritance taxes might be more feasible."),
    ("What's your view on right-to-work laws?", "They weaken unions and reduce bargaining power; I oppose them."),
    ("How do you feel about the Taft-Hartley Act?", "It restricted unions significantly; we should consider reforms that strengthen collective bargaining."),
    ("What's your stance on the H-1B visa program?", "We need skilled immigrants; the program needs reform to prevent abuse and protect workers."),
    ("Should we have a national mask mandate for pandemics?", "During severe outbreaks, yes—public health sometimes requires collective action."),
    ("What's your take on vaccine mandates?", "For schools and healthcare workers, yes; broader mandates are harder to justify."),
    ("How do you feel about the WHO and global health governance?", "We need global coordination for pandemics; defunding weakens everyone."),
    ("What's your view on the opioid crisis and pharmaceutical liability?", "Companies that lied about addiction should be held accountable; we need treatment, not just punishment."),
    ("Should we have a single-payer healthcare system?", "I support it—simpler, covers everyone, reduces administrative waste."),
    ("What's your stance on Medicare negotiation of drug prices?", "Long overdue—other countries do it; we pay far more for the same drugs."),
    ("How do you feel about private prisons?", "The profit motive in incarceration creates perverse incentives; we should phase them out."),
    ("What's your take on cash bail reform?", "Cash bail punishes poverty; we need risk-based assessment and alternatives."),
    ("Should we have a national database of police misconduct?", "Yes—transparency and accountability require tracking patterns."),
    ("What's your view on the 1033 program (military gear to police)?", "Militarizing police undermines community trust; we should scale it back."),
    ("How do you feel about defunding the police?", "Reallocate to prevention and alternatives; some responsibilities don't need armed response."),
    ("What's your stance on civil asset forfeiture?", "It's abused—people lose property without conviction; we need due process reform."),
    ("Should we end the war on terror's authorizations?", "The 2001 AUMF is too broad; we need targeted, time-limited authorizations."),
    ("What's your take on the drone program?", "Necessary tool but needs oversight; civilian casualties and blowback are serious concerns."),
    ("How do you feel about the surveillance state and Patriot Act?", "We've sacrificed too much privacy; reforms are needed to protect civil liberties."),
    ("What's your view on encryption and government backdoors?", "Backdoors undermine security for everyone; strong encryption protects us all."),
    ("Should we have a national data privacy law?", "Yes—we're behind Europe; people deserve control over their data."),
    ("What's your stance on Section 230?", "It enabled the modern internet; we need targeted reform, not repeal."),
    ("How do you feel about antitrust and Big Tech?", "Facebook, Google, Amazon have too much power; we need stronger enforcement."),
    ("What's your take on net neutrality?", "ISPs shouldn't pick winners; we need rules to keep the internet open."),
    ("Should the government fund journalism?", "Indirect support through tax incentives could help; we need a free press."),
    ("What's your view on the FCC and media consolidation?", "We've allowed too much consolidation; diverse voices matter for democracy."),
    ("How do you feel about space exploration funding?", "NASA inspires and drives technology; we should fund it, and private space has a role too."),
    ("What's your stance on AI regulation?", "We need guardrails before harm scales; start with high-risk applications."),
    ("Should we have a cabinet-level Department of Technology?", "Worth considering—technology policy cuts across every domain."),
    ("What's your take on universal broadband?", "Internet is essential infrastructure; we should treat it like electricity and water."),
    ("How do you feel about the Rural Electrification model for broadband?", "Federal investment in underserved areas worked before; we can do it for broadband."),
    ("What's your view on housing-first policies for homelessness?", "Evidence shows it works—stable housing enables people to address other issues."),
    ("Should we upzone more neighborhoods?", "Yes—restrictive zoning drives up costs and sprawl; we need more housing supply."),
    ("What's your stance on inclusionary zoning?", "One tool among many; we need comprehensive housing policy."),
    ("How do you feel about the mortgage interest deduction?", "Subsidizes high earners and McMansions; we should cap or replace it."),
    ("What's your take on community land trusts?", "Innovative model for affordable housing; worth scaling where it works."),
    ("Should we have a federal jobs guarantee?", "Ambitious—pilot it; the idea of employment as a right is compelling."),
    ("What's your view on work requirements for welfare?", "They can help some but often create bureaucracy; childcare and training matter more."),
    ("How do you feel about the Child Tax Credit expansion?", "It dramatically reduced child poverty; we should make it permanent."),
    ("What's your stance on SNAP (food stamps)?", "Essential safety net; we should expand it, not cut it."),
    ("Should we decouple employment from health insurance?", "Yes—tying insurance to jobs traps people and distorts the labor market."),
    ("What's your take on Medicare for All vs. public option?", "I'd prefer Medicare for All but a strong public option could get us there."),
    ("How do you feel about the ACA (Obamacare)?", "It expanded coverage significantly; we should build on it, not repeal."),
    ("What's your view on prescription drug importation?", "Allow it—other countries pay less; we should use that leverage."),
    ("Should we have a public option for broadband?", "Municipal and co-op networks have worked; competition helps."),
    ("What's your stance on right-to-repair laws?", "People should be able to fix their own devices; manufacturers shouldn't lock them out."),
    ("How do you feel about the DMCA and copyright?", "Balance is wrong—too much protection for corporations, not enough for users."),
    ("What's your take on patent reform?", "Patent trolls and overly broad patents stifle innovation; we need reform."),
    ("Should we have a financial transaction tax?", "Could raise revenue and curb speculation; design matters."),
    ("What's your view on the carried interest loophole?", "It's a handout to the wealthy; we should close it."),
    ("How do you feel about the CFPB?", "Essential consumer protection; we should strengthen it, not weaken it."),
    ("What's your stance on payday lending regulation?", "Predatory—we need strong caps on rates and better alternatives."),
    ("Should we have a government-backed digital currency?", "Worth exploring—could improve payments and financial inclusion."),
    ("What's your take on the Fed's independence?", "Independence from political pressure is valuable; accountability is still needed."),
    ("How do you feel about industrial policy?", "Other countries do it; we should strategically invest in key industries."),
    ("What's your view on Buy American provisions?", "Reasonable for some procurement; we need to avoid costly protectionism."),
]

# Pad with additional niche topics
EXTRA_TOPICS = [
    ("view on", "the Hyde Amendment", "It prevents federal funding for abortion and disproportionately harms low-income women; we should repeal it."),
    ("stance on", "congressional stock trading", "Members have insider knowledge; we need a ban or strict blind trusts."),
    ("take on", "the Administrative Procedure Act", "It provides important checks on agency power; reform shouldn't gut it."),
    ("opinion on", "the Chevron deference", "Courts deferring to agencies has pros and cons; the doctrine needs refinement, not elimination."),
    ("view on", "the War Powers Resolution", "It's been ignored; we need a better mechanism for congressional control over military action."),
    ("stance on", "the Insurrection Act", "Too broad—we need limits on presidential power to deploy troops domestically."),
    ("take on", "recess appointments", "A necessary tool when Congress obstructs; norms matter more than legal technicalities."),
    ("opinion on", "executive privilege", "Legitimate for candid advice; it can't shield wrongdoing."),
    ("view on", "the Emoluments Clause", "We should enforce it—presidents shouldn't profit from the office."),
    ("stance on", "the 25th Amendment", "Important backstop; the process for determining incapacity needs clarity."),
    ("take on", "the census and citizenship question", "Adding it was meant to suppress counts; the census should count everyone."),
    ("opinion on", "voting by mail", "Secure and convenient; we should expand it, not restrict it."),
    ("view on", "same-day voter registration", "Removes barriers; states that have it see higher turnout."),
    ("stance on", "automatic voter registration", "Makes sense—if you interact with the DMV, you're registered."),
    ("take on", "the Citizens United decision", "Wrong—money isn't speech; we need a constitutional amendment or new jurisprudence."),
    ("opinion on", "dark money in politics", "Donors should be disclosed; anonymity enables corruption."),
    ("view on", "lobbying disclosures", "We need real-time, comprehensive disclosure; sunshine is the best disinfectant."),
    ("stance on", "revolving door between government and industry", "Cooling-off periods help; we need stronger ethics enforcement."),
    ("take on", "the Jones Act and Puerto Rico", "It raises costs for an island territory; we should exempt or reform for disaster relief."),
    ("opinion on", "the Jones Act generally", "Protectionist; benefits a few at the cost of many."),
    ("view on", "the federal gas tax", "Hasn't been raised in decades; we need revenue for infrastructure."),
    ("stance on", "vehicle mileage fees", "Fairer than gas tax as vehicles electrify; we should pilot it."),
    ("take on", "highway funding and transit", "We over-invest in roads; we need more balance for transit and rail."),
    ("opinion on", "AMTRAK and passenger rail", "Underfunded for decades; we should invest in a national network."),
    ("view on", "airport infrastructure", "Our airports lag the world; we need modernized facilities."),
    ("stance on", "port and shipping infrastructure", "Supply chain bottlenecks showed we've underinvested; we need to catch up."),
    ("take on", "critical minerals and domestic sourcing", "Security and supply chain resilience matter; we need strategic investment."),
    ("opinion on", "rare earth elements policy", "China dominates; we need diversification and recycling."),
    ("view on", "semiconductor subsidies (CHIPS Act)", "Strategic—we can't rely on Taiwan for everything; industrial policy makes sense here."),
    ("stance on", "battery manufacturing incentives", "Essential for EVs; we need domestic capacity."),
    ("take on", "the Strategic Petroleum Reserve", "Useful buffer; we should maintain it and use it during shocks."),
    ("opinion on", "oil and gas leasing on public lands", "We should reduce it as we transition; royalties could fund renewables."),
    ("view on", "tribal sovereignty", "Tribes are nations; we should honor treaties and support self-determination."),
    ("stance on", "Native American voting rights", "Tribes face unique barriers; we need resources and accommodations."),
    ("take on", "the Indian Child Welfare Act", "Protects tribal communities; it's been upheld for good reason."),
    ("opinion on", "reparations for slavery", "The moral case is strong; we need a commission to study forms and implementation."),
    ("view on", "the 1619 Project", "It reframes history meaningfully; debates about it reflect how we understand our past."),
    ("stance on", "critical race theory in schools", "Most critics don't understand it; teaching honest history isn't indoctrination."),
    ("take on", "teaching about racism in K-12", "Students should learn the full history; it makes them better citizens."),
    ("opinion on", "book bans in schools", "Dangerous—parents can guide their kids; they shouldn't dictate for everyone."),
    ("view on", "school board politics", "Local control matters but culture war fights distract from education."),
    ("stance on", "charter schools", "Some are excellent; we need accountability so bad ones don't harm kids."),
    ("take on", "teacher pay", "Teachers are underpaid; we need to invest in the profession."),
    ("opinion on", "standardized testing and teaching to the test", "We've over-indexed; it narrows curriculum and stresses everyone."),
    ("view on", "school funding and property taxes", "Funding by property tax entrenches inequality; we need more state and federal support."),
    ("stance on", "community colleges and free tuition", "Huge ROI; we should make two-year degrees free or cheap."),
    ("take on", "student loan forgiveness", "Targeted relief makes sense; the system is broken and needs reform."),
    ("opinion on", "income-driven repayment", "Good idea; we should make it more generous."),
    ("view on", "for-profit colleges", "Many are predatory; we need stricter oversight and accountability."),
    ("stance on", "apprenticeships and vocational training", "Underfunded; we need more pathways that don't require a four-year degree."),
    ("take on", "the future of work and automation", "We need policy to help workers transition; Luddism won't work."),
    ("opinion on", "right to disconnect laws", "Work-life balance matters; some countries have shown it works."),
    ("view on", "four-day work week", "Pilots show productivity can hold; worth exploring."),
    ("stance on", "remote work and tax implications", "Creates complicated questions; we need clearer rules."),
    ("take on", "the PRO Act", "Would make unionizing easier; we need to restore bargaining power."),
    ("opinion on", "right-to-work laws", "They weaken unions; I oppose them."),
    ("view on", "sectoral bargaining", "High-road employers shouldn't compete with low-road; sectoral agreements level the field."),
    ("stance on", "co-determination (worker seats on boards)", "German model has merits; worth considering for large firms."),
    ("take on", "the gig economy and benefits", "Portable benefits could help; we need new frameworks."),
    ("view on", "congressional term limits", "Would reduce institutional knowledge but curb career politicians; I'm conflicted."),
    ("stance on", "the line-item veto", "Gives presidents too much power over spending; Congress should do its job."),
    ("take on", "earmarks in appropriations", "They grease the wheels; transparency and limits matter more than banning."),
    ("opinion on", "the debt ceiling as leverage", "Holding the economy hostage is irresponsible; we need to fix the process."),
    ("view on", "foreign lobbying registration", "We need to know who's influencing policy and for whom."),
    ("stance on", "the Congressional Review Act", "Useful check on regulations; recent use has been aggressive."),
    ("take on", "government shutdowns", "They harm workers and services; we should make them impossible."),
    ("opinion on", "continuing resolutions", "Better than shutdowns but we need real budgets and planning."),
    ("view on", "the budget reconciliation process", "Useful for fiscal legislation; the rules create odd constraints."),
    ("stance on", "entitlement reform", "Social Security and Medicare need adjustments; cuts alone won't work."),
    ("take on", "raising the retirement age", "Life expectancy varies by income; we need a fairer approach."),
    ("opinion on", "privatizing Social Security", "Risky—market downturns would devastate retirees; the current system works."),
    ("view on", "Medicare Advantage", "Plans vary; we need to ensure they don't underserve beneficiaries."),
    ("stance on", "negotiating drug prices in Medicare", "Long overdue; other countries do it and pay far less."),
    ("take on", "the public health service corps", "Undervalued—we need more investment in public health workforce."),
    ("opinion on", "mental health parity laws", "Good start; enforcement and network adequacy remain problems."),
    ("view on", "surprise medical billing reform", "Patients shouldn't be caught in the middle; the law helped."),
    ("stance on", "hospital price transparency", "Prices should be public; compliance has been weak."),
    ("take on", "certificate of need laws", "Often protect incumbents; we should scrutinize them."),
    ("opinion on", "scope of practice for nurse practitioners", "NPs can safely provide many services; outdated restrictions hurt access."),
    ("view on", "telehealth permanence", "Expanded access during COVID; we should make it permanent where it works."),
    ("stance on", "the 340B drug discount program", "Helps safety-net providers; we should protect it from cuts."),
    ("take on", "prior authorization in insurance", "Often used to deny care; we need reforms and appeals."),
    ("opinion on", "step therapy requirements", "Can delay needed treatments; exceptions should be easier."),
    ("view on", "biosimilar competition", "Could reduce drug costs; we need to remove barriers to entry."),
    ("stance on", "the orphan drug act", "Incentivizes rare disease R&D; some companies game it."),
    ("take on", "accelerated FDA approval", "Gets drugs to patients faster; we need post-market surveillance."),
    ("opinion on", "right-to-try laws", "Emotional appeal but FDA expanded access exists; these laws can mislead."),
    ("view on", "the VA healthcare system", "Has improved but still struggles; we need continued reform and funding."),
    ("stance on", "veterans' benefits expansion", "We owe it to those who served; we should streamline and expand access."),
    ("take on", "Agent Orange and burn pit exposure", "We need to presume service connection; veterans shouldn't have to prove it."),
    ("opinion on", "military housing conditions", "Unacceptable—we need accountability and investment."),
    ("view on", "the Selective Service", "Outdated; we have a volunteer military; we should abolish it or make it gender-neutral."),
    ("stance on", "women in combat roles", "They've proven themselves; the military is stronger for it."),
    ("take on", "transgender military service", "Anyone who meets standards should serve; the ban was discriminatory."),
    ("opinion on", "military recruitment challenges", "Pay, benefits, and culture matter; we need to compete for talent."),
    ("view on", "defense contractor oversight", "Waste and fraud are real; we need stronger accountability."),
    ("stance on", "the F-35 program", "Over budget and delayed but we're committed; lessons for future procurement."),
    ("take on", "nuclear modernization", "Deterrence requires credible capability; we need to balance cost and need."),
    ("opinion on", "the Space Force", "Makes sense as domain evolves; whether it needed to be separate is debatable."),
    ("view on", "cyber command and military role", "Cyber is a domain; we need capabilities and doctrine."),
    ("stance on", "climate and national security", "Threat multiplier—DOD takes it seriously; we should too."),
    ("take on", "military base closures (BRAC)", "Politically hard but sometimes necessary; we need a process."),
    ("opinion on", "veteran-to-civilian transition", "We underinvest; job training and mental health support are critical."),
    ("view on", "the GI Bill and education benefits", "Valuable investment; we should protect and expand it."),
    ("stance on", "predatory for-profit schools targeting veterans", "Disgraceful; we need enforcement and borrower relief."),
    ("take on", "the Berry Amendment (domestic sourcing)", "Protects defense-industrial base; can raise costs."),
    ("opinion on", "export controls on technology", "Necessary for national security; we need to balance with competitiveness."),
    ("view on", "CFIUS and foreign investment review", "Important for protecting critical assets; process should be predictable."),
    ("stance on", "decoupling from Chinese supply chains", "Risk reduction makes sense; full decoupling is costly and difficult."),
    ("take on", "the Trans-Pacific Partnership without the US", "We lost influence; rejoining or building alternatives could help."),
    ("opinion on", "the African Growth and Opportunity Act", "Trade preference program helps development; we should sustain it."),
    ("view on", "sanctions on Venezuela", "Mixed results; ordinary people suffer; we need humanitarian carve-outs."),
    ("stance on", "Cuba policy", "Decades of embargo haven't worked; engagement could help."),
    ("take on", "the Mexico-Canada trade relationship", "Critical for North American competitiveness; we need to strengthen it."),
    ("opinion on", "migration from Central America", "Root causes matter—we need investment in the region, not just enforcement."),
    ("view on", "DACA and Dreamers", "These young people are Americans in every way; we need a permanent solution."),
    ("stance on", "TPS (Temporary Protected Status)", "Needed for countries in crisis; we should make pathways to permanence."),
    ("take on", "asylum backlog and processing", "We need more judges and staff; the system is overwhelmed."),
    ("opinion on", "detention of immigrants", "Should be rare; alternatives to detention work and cost less."),
    ("view on", "family separation at the border", "It was cruel and traumatic; we must never do it again."),
    ("stance on", "the Remain in Mexico policy", "Put vulnerable people at risk; we need safer alternatives."),
    ("take on", "Title 42 and pandemic-era expulsion", "Was a public health pretext for restriction; we need fair process."),
    ("opinion on", "the visa system and backlogs", "Broken—years of wait for some categories; we need reform and resources."),
    ("view on", "high-skilled immigration", "We're losing talent to Canada and others; we need more visas and paths to green cards."),
    ("stance on", "agricultural guest workers", "Farmers need workers; we need a functional H-2A program with protections."),
    ("take on", "birthright citizenship", "It's in the Constitution and has served us well; changing it would be wrong."),
    ("opinion on", "sanctuary cities", "Local trust with police matters for public safety; federal coercion is problematic."),
    ("view on", "E-verify mandates", "Accuracy matters; errors hurt workers; we need a better system."),
    ("stance on", "the border wall", "Symbol over substance; money better spent on personnel and technology."),
    ("take on", "border technology and surveillance", "Can improve security and processing; we need oversight of data use."),
    ("opinion on", "immigration court and representation", "People need lawyers; we should provide counsel for vulnerable populations."),
    ("view on", "merit-based immigration", "Skills matter but family ties do too; we need a balanced system."),
    ("stance on", "diversity visas", "Small program with outsized impact; we should keep it."),
    ("take on", "refugee resettlement capacity", "We've cut it drastically; we should restore and expand."),
    ("opinion on", "humanitarian parole", "Flexible tool; we need clear criteria and fair process."),
    ("view on", "the U.S. and international climate finance", "We've underfunded; developing countries need support for transition."),
    ("stance on", "loss and damage funding", "Rich countries bear responsibility; we should contribute."),
    ("take on", "the Paris Agreement", "Imperfect but the best framework we have; we should stay and lead."),
    ("opinion on", "emissions trading vs. carbon tax", "Either can work; what matters is stringency and coverage."),
    ("view on", "green jobs and just transition", "Workers in fossil fuels need retraining; we can't leave communities behind."),
    ("stance on", "offshore wind development", "Huge potential; we're finally building; we need to scale."),
    ("take on", "solar tariffs", "Protectionism that slows adoption; we need domestic capacity through investment."),
    ("opinion on", "critical minerals for clean energy", "Supply chain vulnerability; we need domestic sourcing and recycling."),
    ("view on", "hydrogen as a fuel", "Potential for heavy industry and transport; we need to invest in the ecosystem."),
    ("stance on", "carbon capture and storage", "Worth investing in; we may need it for hard-to-decarbonize sectors."),
    ("take on", "direct air capture", "Early stage; could be part of the portfolio; shouldn't replace mitigation."),
    ("opinion on", "forest conservation and REDD+", "Forests are crucial; we need to fund protection properly."),
    ("view on", "agricultural emissions", "Under-discussed; soil health and practices can help."),
    ("stance on", "methane regulations", "Quick win—methane is powerful and short-lived; we should crack down."),
    ("take on", "the social cost of carbon", "Essential for policy analysis; we should use best available science."),
    ("opinion on", "environmental justice", "Communities of color bear disproportionate burden; we need targeted action."),
    ("view on", "superfund site cleanup", "Underfunded for decades; we need to accelerate."),
    ("stance on", "PFAS regulation", "These forever chemicals are everywhere; we need comprehensive action."),
    ("take on", "lead pipe replacement", "No safe level of lead; we should fund full replacement."),
    ("opinion on", "flood insurance and climate risk", "Premiums don't reflect risk; we need reform and retreat from some areas."),
]


def build_extra_qa(extras: list[tuple]) -> list[tuple[str, str]]:
    pairs = []
    for kind, topic, answer in extras:
        if kind == "view on":
            question = f"What's your view on {topic}?"
        elif kind == "stance on":
            question = f"What's your stance on {topic}?"
        elif kind == "take on":
            question = f"What's your take on {topic}?"
        elif kind == "opinion on":
            question = f"What's your opinion on {topic}?"
        else:
            question = f"What's your {kind} {topic}?"
        pairs.append((question, answer))
    return pairs


def generate_niche_data() -> dict:
    all_qa = list(QA_PAIRS)
    extras = build_extra_qa(EXTRA_TOPICS)
    all_qa.extend(extras)

    entries = []
    for i, (q, a) in enumerate(all_qa):
        entries.append({"id": i, "question": q, "answer": a})

    return {"total": len(entries), "qa_pairs": entries}


if __name__ == "__main__":
    data = generate_niche_data()
    with open("niche_political_questions.json", "w") as f:
        json.dump(data, f, indent=2)
    print(f"Generated {data['total']} unique political Q/A pairs.")
